<?php

declare(strict_types=1);

use GardenLawn\Core\ViewModel\Gallery;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */

$galleryViewModel = $viewModels->require(Gallery::class);
$worksInfo = $galleryViewModel->getWorksInfo();

?>
<link rel="stylesheet" type="text/css"
      href="<?= $escaper->escapeUrl($block->getViewFileUrl('css/slider-pro.css')) ?>" media="screen"/>

<div
    x-data="gardenLawnCoreGallery" data-hyvacsp1='<?= json_encode($worksInfo, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) ?>'
    id="sliders"
    class="gallery-grid"
>
    <div class="row">
        <template x-for="item in galleries" :key="gardenLawnCoreGalleryKey1">
            <div class="text-center gallery-div column div-bordered-blue" style="margin:5px;">
                <h3 class="text-2xl font-medium text-gray-900 title-font text-center" x-text="gardenLawnCoreGalleryText2"></h3>
                <div class="slider-pro" :id="gardenLawnCoreGalleryId3" x-init="gardenLawnCoreGalleryInit4">
                    <div class="sp-slides">
                        <template x-for="image in gardenLawnCoreGalleryFor5" :key="gardenLawnCoreGalleryKey6">
                            <div class="sp-slide">
                                <img class="sp-image"
                                     :data-src="gardenLawnCoreGalleryDataSrc7"
                                     :alt="gardenLawnCoreGalleryAlt8"
                                     :height="gardenLawnCoreGalleryHeight9"
                                     :width="gardenLawnCoreGalleryWidth10" />
                            </div>
                        </template>
                    </div>
                    <div class="sp-thumbnails">
                        <template x-for="image in gardenLawnCoreGalleryFor5" :key="gardenLawnCoreGalleryKey6">
                            <img class="sp-thumbnail"
                                 :src="gardenLawnCoreGallerySrc13"
                                 :alt="gardenLawnCoreGalleryAlt8"
                                 :height="gardenLawnCoreGalleryHeight9"
                                 :width="gardenLawnCoreGalleryWidth10" />
                        </template>
                    </div>
                </div>
            </div>
        </template>
    </div>
</div>
