<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */

/** Generated with hyva-csp-helper.php */
?>
<script>
<?php /** Generated with hyva-csp-helper.php */ ?>
function gardenLawnCoreGallery() {
    return Object.assign(
        {
        galleries: JSON.parse(this.$el.dataset.hyvacsp1),
        initSlider(id) {
            $(this.id).sliderPro({
                imageScaleMode: "contain",
                arrows: true,
                fadeArrows: false,
                fullscreen: true,
                fadeFullscreen: false,
                buttons: false,
                waitForLayers: true,
                autoplay: false,
                autoScaleLayers: false,
                thumbnailHeight: 50,
                thumbnailsPosition: "bottom",
                thumbnailPointer: false,
                thumbnailArrows: true,
                fadeThumbnailArrows: false,
                thumbnailTouchSwipe: true,
                fullScreen: true
            }).resize();

            let this.slider = $(this.id);
            let this.fullscreen = find(".sp-full-screen-button");
            css("display", "none");
            find(".sp-slide").on("click", function () {
                if (!hasClass("sp-swiping")) {
                    trigger("click");
                }
            });
        }
    }
        ,{
            ['gardenLawnCoreGalleryAlt14']() {return this.image.title},
            ['gardenLawnCoreGalleryAlt8']() {return this.image.title},
            ['gardenLawnCoreGalleryDataSrc7']() {return this.image.link},
            ['gardenLawnCoreGalleryFor11']() {return this.item.images},
            ['gardenLawnCoreGalleryFor5']() {return this.item.images},
            ['gardenLawnCoreGalleryHeight15']() {return this.image.height},
            ['gardenLawnCoreGalleryHeight9']() {return this.image.height},
            ['gardenLawnCoreGalleryId3']() {return 'my-slider-' + this.item.id},
            ['gardenLawnCoreGalleryInit4']() {return this.initSlider('#my-slider-' + this.item.id)},
            ['gardenLawnCoreGalleryKey1']() {return this.item.id},
            ['gardenLawnCoreGalleryKey12']() {return this.image.link},
            ['gardenLawnCoreGalleryKey6']() {return this.image.link},
            ['gardenLawnCoreGallerySrc13']() {return this.image.thumb},
            ['gardenLawnCoreGalleryText2']() {return this.item.id},
            ['gardenLawnCoreGalleryWidth10']() {return this.image.width},
            ['gardenLawnCoreGalleryWidth16']() {return this.image.width},
        }
    )
}
window.addEventListener('alpine:init', () => Alpine.data('gardenLawnCoreGallery', gardenLawnCoreGallery), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>