<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */

/** Generated with hyva-csp-helper.php */
?>
<script>
    const tag = document.createElement('script');
    tag.src = "https://www.youtube.com/iframe_api";
    const firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

    let players = [];

    function onYouTubeIframeAPIReady() {
        <?php foreach ($itemsVideo1 as $video): ?>
        players.push(
            new YT.Player('<?php echo $video['divId']; ?>', {
                videoId: '<?php echo $video['videoId']; ?>',
                events: {
                    'onStateChange': onPlayerStateChange
                }
            }));
        <?php endforeach; ?>
    }

    function onPlayerStateChange(event) {
        for (let i in players) {
            if (event.target.getPlayerState() === YT.PlayerState.PLAYING &&
                players[i].g.id !== event.target.g.id &&
                players[i].getPlayerState() === YT.PlayerState.PLAYING
            ) {
                players[i].stopVideo();
            }
        }
    }
</script>
<?php $hyvaCsp->registerInlineScript() ?>

<script>
function viewFrontendTemplatesGardenlighting_rightMovedScript0() {
    const el = this.$el,
          wire = this.$wire;
    
    // @todo Implement interaction with the original code ^^
<?php /** Variables from "./view/frontend/templates/gardenlighting_right.phtml" */ ?>
<?php /** References (`$itemsVideo1`, `$video`) */ ?>
    
    return {
        init() {}
    }
}
window.addEventListener('alpine:init', () => Alpine.data('viewFrontendTemplatesGardenlighting_rightMovedScript0', viewFrontendTemplatesGardenlighting_rightMovedScript0), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>