<?php declare(strict_types=1);

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */
/** @var Slider $sliderViewModel */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\Slider;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

$sliderViewModel = $viewModels->require(Slider::class);
$itemsVideoTemplate = 'GardenLawn_Core::slider-youtube-item.phtml';
$itemsVideo1 = [
    ['divId' => 'video1', 'videoId' => '53Iz2uHDYrE'],
    ['divId' => 'video2', 'videoId' => 'RBrzXBKfZ9s'],
    ['divId' => 'video3', 'videoId' => 'UtSeV5e1fjU'],
    ['divId' => 'video4', 'videoId' => 'iGyPUnknuWA']
];
?>
<div class="lg:w-1/3">
    <div class="div-bordered-blue">
    <?=
    $sliderViewModel->getSliderForItems($itemsVideoTemplate, $itemsVideo1)
        //->setData('title', __('Wideo'))
        ->toHtml()
    ?></div></div>
<div x-data="gardenLawnCoreGardenlightingRight">
<?php /** Moved variables previously here to "./view/frontend/templates/gardenlighting_right-csp-js.phtml" */ ?>
<?php /** References (`$itemsVideo1`, `$video`) */ ?>
</div><?php $hyvaCsp->registerInlineScript() ?>
<script>
<?php /** Generated with hyva-csp-helper.php */ ?>
function gardenLawnCoreGardenlightingRight() {
    return Object.assign(
        viewFrontendTemplatesGardenlighting_rightMovedScript0.call(this)
    )
}
window.addEventListener('alpine:init', () => Alpine.data('gardenLawnCoreGardenlightingRight', gardenLawnCoreGardenlightingRight), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>