<?php

declare(strict_types=1);

use GardenLawn\Core\ViewModel\VideoSlider;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Slider;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

$sliderViewModel = $viewModels->require(Slider::class);
$videoSliderViewModel = $viewModels->require(VideoSlider::class);

$itemsVideo1 = [
    ['divId' => 'video1', 'videoId' => '9B3OeSeHj2E'],
    ['divId' => 'video2', 'videoId' => 'GddYRaUZAR4']
];
$itemsVideo2 = [
    ['divId' => 'video3', 'videoId' => '2KZ0YCTZD4I'],
    ['divId' => 'video4', 'videoId' => 'vj_3ifs16Cs'],
    ['divId' => 'video5', 'videoId' => 'IkP6xPNSMnU'],
    ['divId' => 'video6', 'videoId' => 'cMbxYqPruSc'],
    ['divId' => 'video7', 'videoId' => 'AaHyRWbYhLc']
];
$itemsVideo3 = [
    ['divId' => 'video8', 'videoId' => 'jYrCjkKTfdM'],
    ['divId' => 'video9', 'videoId' => '_-kUrFIZhwE']
];
$itemsVideo4 = [
    ['divId' => 'video10', 'videoId' => 'hanGczLa-Yc'],
    ['divId' => 'video11', 'videoId' => 'OW7HKXX-Esc'],
    ['divId' => 'video12', 'videoId' => '271DxnmJ9iw']
];
?>
<div class="lg:w-1/3">
    <div class="div-bordered-blue">
        <?php
        echo $block->getLayout()
            ->createBlock(Template::class)
            ->setTemplate('GardenLawn_Core::video-slider.phtml')
            ->setData('sliderViewModel', $sliderViewModel)
            ->setData('videoSliderViewModel', $videoSliderViewModel->setVideoData($itemsVideo1))
            ->toHtml();

        echo $block->getLayout()
            ->createBlock(Template::class)
            ->setTemplate('GardenLawn_Core::video-slider.phtml')
            ->setData('sliderViewModel', $sliderViewModel)
            ->setData('videoSliderViewModel', $videoSliderViewModel->setVideoData($itemsVideo2))
            ->toHtml();

        echo $block->getLayout()
            ->createBlock(Template::class)
            ->setTemplate('GardenLawn_Core::video-slider.phtml')
            ->setData('sliderViewModel', $sliderViewModel)
            ->setData('videoSliderViewModel', $videoSliderViewModel->setVideoData($itemsVideo3))
            ->toHtml();

        echo $block->getLayout()
            ->createBlock(Template::class)
            ->setTemplate('GardenLawn_Core::video-slider.phtml')
            ->setData('sliderViewModel', $sliderViewModel)
            ->setData('videoSliderViewModel', $videoSliderViewModel->setVideoData($itemsVideo4))
            ->toHtml();
        ?>
    </div>
</div>
