<?php declare(strict_types=1);

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */
/** @var Slider $sliderViewModel */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\Slider;
use Magento\Catalog\Block\Product\View;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var View $block */
$product = $block->getProduct();
$sliderViewModel = $viewModels->require(Slider::class);
$itemsVideoTemplate = 'GardenLawn_Core::slider-youtube-item.phtml';
$itemsVideo = [
    ['divId' => 'video1', 'videoId' => 'ZW0THAI6G7I'],
    ['divId' => 'video2', 'videoId' => 'cBsLcsb8PRg'],
    ['divId' => 'video3', 'videoId' => 'PVDK3esEKr8'],
    ['divId' => 'video4', 'videoId' => 'ryt9oYCqWIs']
];

$product = $block->getProduct();
?>
<style type="text/css">
    iframe {
        overflow: hidden !important;
        -ms-overflow-style: none !important; /* IE and Edge */
        scrollbar-width: none !important; /* Firefox */
    }

    iframe::-webkit-scrollbar {
        display: none !important;
        background-color: transparent !important;
    }

    iframe::-webkit-scrollbar {
        width: 0px !important;
        height: 0px !important;
        background-color: transparent !important;
    }

    iframe::-webkit-scrollbar-button {
        width: 0px !important;
        height: 0px !important;
        background-color: transparent !important;
    }

    iframe::-webkit-scrollbar-thumb {
        background-color: transparent !important;
        border: 0px none !important;
        border-radius: 0px !important;
    }

    iframe::-webkit-scrollbar-thumb:hover {
        background-color: transparent !important;
    }

    iframe::-webkit-scrollbar-thumb:active {
        background-color: transparent !important;
    }

    iframe::-webkit-scrollbar-track {
        background-color: transparent !important;
        border: 0px none !important;
        border-radius: 0px !important;
    }

    iframe::-webkit-scrollbar-track:hover {
        background-color: transparent !important;
    }

    iframe::-webkit-scrollbar-track:active {
        background-color: transparent !important;
    }

    iframe::-webkit-scrollbar-corner {
        background-color: transparent !important;
    }

    .topnav a {
        text-align: center;
    }
</style>
<section class="text-gray-700 body-font">
    <div class="flex pb-6 md:py-6 lg:flex-row flex-col items-center">
        <div
            class="grid grid-rows-auto grid-cols-1 md:gap-x-5 md:grid-cols-[42%_minmax(0,_1fr)] md:grid-rows-[min-content_minmax(0,_1fr)] lg:gap-x-10 lg:grid-cols-2 w-full">
            <?= $block->getChildHtml('product.title') ?>
            <?= $block->getChildHtml('product.media') ?>
            <div>
                <?= $block->getChildHtml('product.info') ?>
                <div id="product-attribute"></div>
                <div id="yt-video">
                    <?= $sliderViewModel->getSliderForItems($itemsVideoTemplate, $itemsVideo)->toHtml() ?>
                </div>
            </div>
        </div>
    </div>
    <div class="flex pb-10 md:py-10 lg:flex-row flex-col items-center">
        <?= $block->getChildHtml('product.info.details'); ?>
    </div>
</section>
<section>
    <?= $block->getChildHtml('product_options_wrapper_bottom') ?>
</section>


<div id="tabs-description">
    <div class="tabs-container" data-content-type="tabs" data-appearance="default" data-active-tab=""
         data-element="main"
         style="padding: 0; margin-left: -23px;">
        <ul role="tablist" style=" text-align: center;" class="tabs-navigation" data-element="navigation">
            <li role="tab" class="tab-header active" data-element="headers"><a href="#tab_1" class="tab-title"><span
                        class="tab-title">Trawa z rolki</span></a></li>
            <li role="tab" class="tab-header" data-element="headers"><a href="#tab_2" class="tab-title"
                                                                        onclick="loadIframe(this)"><span
                        class="tab-title">O producencie</span></a></li>
            <li role="tab" class="tab-header" data-element="headers"><a href="#tab_3" class="tab-title"
                                                                        onclick="loadIframe(this)"><span
                        class="tab-title">Grupa Trawnik</span></a></li>
            <li role="tab" class="tab-header" data-element="headers"><a href="#tab_4" class="tab-title"
                                                                        onclick="loadIframe(this)"><span
                        class="tab-title">Trawa ogrodowa</span></a></li>
            <li role="tab" class="tab-header" data-element="headers"><a href="#tab_5" class="tab-title"
                                                                        onclick="loadIframe(this)"><span
                        class="tab-title">Logistyka</span></a></li>
            <li role="tab" class="tab-header" data-element="headers"><a href="#tab_6" class="tab-title"
                                                                        onclick="loadIframe(this)"><span
                        class="tab-title">Poradnik</span></a></li>
            <li role="tab" class="tab-header" data-element="headers"><a href="#tab_7" class="tab-title"
                                                                        onclick="loadIframe(this)"><span
                        class="tab-title">FAQ</span></a></li>
        </ul>
        <div id="tab-content" class="tabs-content" data-element="content" style="width: 100%;">
            <div data-content-type="tab-item" data-appearance="default" data-tab-name="test 1"
                 data-background-images="{}"
                 data-element="main" id="tab_1" style="padding: 0">
                <iframe id="iframe_1" style="width: 100%; overflow:hidden;" frameborder="0" scrolling="no"
                        onload="resizeIframe(this)"
                        src="/hyvaroot/pages/grassinfo1"></iframe>
            </div>
            <div data-content-type="tab-item" data-appearance="default" data-tab-name="test 2"
                 data-background-images="{}"
                 data-element="main" id="tab_2" style="padding: 0">
                <iframe id="iframe_2" style="width: 100%; overflow:hidden;" frameborder="0" scrolling="no"
                        src=""></iframe>
            </div>
            <div data-content-type="tab-item" data-appearance="default" data-tab-name="test 3"
                 data-background-images="{}"
                 data-element="main" id="tab_3" style="padding: 0">
                <iframe id="iframe_3" style="width: 100%; overflow:hidden;" frameborder="0" scrolling="no"
                        src=""></iframe>
            </div>
            <div data-content-type="tab-item" data-appearance="default" data-tab-name="test 4"
                 data-background-images="{}"
                 data-element="main" id="tab_4" style="padding: 0">
                <iframe id="iframe_4" style="width: 100%; overflow:hidden;" frameborder="0" scrolling="no"
                        src=""></iframe>
            </div>
            <div data-content-type="tab-item" data-appearance="default" data-tab-name="test 5"
                 data-background-images="{}"
                 data-element="main" id="tab_5" style="padding: 0">
                <iframe id="iframe_5" style="width: 100%; overflow:hidden;" frameborder="0" scrolling="no"
                        src=""></iframe>
            </div>
            <div data-content-type="tab-item" data-appearance="default" data-tab-name="test 6"
                 data-background-images="{}"
                 data-element="main" id="tab_6" style="padding: 0">
                <iframe id="iframe_6" style="width: 100%; overflow:hidden;" frameborder="0" scrolling="no"
                        src=""></iframe>
            </div>
            <div data-content-type="tab-item" data-appearance="default" data-tab-name="test 7"
                 data-background-images="{}"
                 data-element="main" id="tab_7" style="padding: 0">
                <iframe id="iframe_7" style="width: 100%; overflow:hidden;" frameborder="0" scrolling="no"
                        src=""></iframe>
            </div>
        </div>
    </div>
</div>
<div x-data="gardenLawnCoreLawnsinrollDescription">
<?php /** Moved variables previously here to "./view/frontend/templates/lawnsinroll_description-csp-js.phtml" */ ?>
<?php /** References (`$itemsVideo`, `$video`) */ ?>
</div><?php $hyvaCsp->registerInlineScript() ?>
<script>
<?php /** Generated with hyva-csp-helper.php */ ?>
function gardenLawnCoreLawnsinrollDescription() {
    return Object.assign(
        viewFrontendTemplatesLawnsinroll_descriptionMovedScript0.call(this)
    )
}
window.addEventListener('alpine:init', () => Alpine.data('gardenLawnCoreLawnsinrollDescription', gardenLawnCoreLawnsinrollDescription), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>