<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */

/** Generated with hyva-csp-helper.php */
?>
<script>
    function gardenLawnCorePoolrobotsRight() {
        return {
            initPhotoSwipe() {
                if (Alpine.store('HYVA_PHOTO_SWIPE').is_loaded) {
                    new PhotoSwipeLightbox({
                        gallery: '#my-gallery',
                        children: 'a',
                        pswpModule: PhotoSwipe
                    }).init();
                }
            }
        }
    }
    window.addEventListener('alpine:init', () => Alpine.data('gardenLawnCorePoolrobotsRight', gardenLawnCorePoolrobotsRight), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>
