<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */

$showTitle = $block->getShowTitle() !== null ? $block->getShowTitle() : true;
$defaultWidth = 270;
$defaultHeight = 95;

$items = [
    [
        'src' => 'https://pub.gardenlawn.pl/media/producers/am-robots.webp',
        'alt' => 'am-robots'
    ],
    [
        'src' => 'https://pub.gardenlawn.pl/media/producers/AmbrogioRobotVerde.webp',
        'alt' => 'AmbrogioRobotVerde'
    ],
    [
        'src' => 'https://pub.gardenlawn.pl/media/producers/BB_logo_LS_yellow_RGB.webp',
        'alt' => 'BB_logo_LS_yellow_RGB'
    ],
    [
        'src' => 'https://pub.gardenlawn.pl/media/producers/FX_Logo_100Black.webp',
        'alt' => 'FX_Logo_100Black'
    ],
    [
        'src' => 'https://pub.gardenlawn.pl/media/producers/Hunter-Hydrawise_logo.webp',
        'alt' => 'Hunter-Hydrawise_logo'
    ],
    [
        'src' => 'https://pub.gardenlawn.pl/media/producers/LOGOTECH.webp',
        'alt' => 'LOGOTECH'
    ],
    [
        'src' => 'https://pub.gardenlawn.pl/media/producers/cropped-cropped-LOGO-SUMIN-1-100x41.webp',
        'alt' => 'cropped-cropped-LOGO-SUMIN'
    ],
    [
        'src' => 'https://pub.gardenlawn.pl/media/producers/designfx.webp',
        'alt' => 'designfx'
    ],
    [
        'src' => 'https://pub.gardenlawn.pl/media/producers/finn.webp',
        'alt' => 'finn'
    ],
    [
        'src' => 'https://pub.gardenlawn.pl/media/producers/irrigationfx.webp',
        'alt' => 'irrigationfx'
    ],
    [
        'src' => 'https://pub.gardenlawn.pl/media/producers/landfx-logo-800w.webp',
        'alt' => 'landfx-logo'
    ],
    [
        'src' => 'https://pub.gardenlawn.pl/media/producers/logo nemh2o azzurro.webp',
        'alt' => 'logo nemh2o azzurro'
    ],
    [
        'src' => 'https://pub.gardenlawn.pl/media/producers/plantingfx.webp',
        'alt' => 'plantingfx'
    ],
    [
        'src' => 'https://pub.gardenlawn.pl/media/producers/rblogo_pms348.webp',
        'alt' => 'rblogo_pms348'
    ],
    [
        'src' => 'https://pub.gardenlawn.pl/media/producers/target_cmyk.webp',
        'alt' => 'target_cmyk'
    ],
    [
        'src' => 'https://pub.gardenlawn.pl/media/producers/toro-logo-RGB-for-digital.webp',
        'alt' => 'toro-logo'
    ],
    [
        'src' => 'https://pub.gardenlawn.pl/media/producers/trawnik_producent.webp',
        'alt' => 'trawnik_producent'
    ]
];

$marqueeClasses = "flex gap-[var(--gap)] select-none overflow-hidden mask-overflow border-y border-gray-300 py-5 md:py-3";
$marqueeGroupClasses = "shrink-0 flex gap-[var(--gap)] items-center justify-around min-w-full" .
    " animate-[marqueeScroll_var(--duration)_linear_infinite] motion-reduce:[animation-play-state:paused]";
?>

<section
    class="relative"
    style="--size: clamp(10rem, 1rem + 40vmin, 30rem); --gap: calc(var(--size) / 14); --duration: 40s;"
    aria-label="<?= $escaper->escapeHtml(__('Our favorite brands')) ?>"
>
    <?php if ($showTitle): ?>
        <div class="mb-4 sm:flex sm:justify-between sm:items-baseline">
            <div class="hidden text-3xl leading-9 font-bold text-gray-800">
                <?= $escaper->escapeHtml(__('Our favorite brands')) ?>
            </div>
            <a
                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                class="hidden text-blue-700 text-lg leading-7 font-semibold"
            >
                <?= $escaper->escapeHtml(__('Browse all brands')) ?> →
            </a>
        </div>
    <?php endif; ?>

    <div class="<?= $escaper->escapeHtmlAttr($marqueeClasses) ?>">
        <div class="<?= $escaper->escapeHtmlAttr($marqueeGroupClasses) ?>">
            <?php foreach ($items as $item): ?>
                <img
                    class="h-16 w-auto object-contain"
                    style="max-width: 120px;"
                    src="<?= $escaper->escapeHtmlAttr($item['src']) ?>"
                    alt="<?= $escaper->escapeHtmlAttr($item['alt'] ?? '') ?>"
                    width="<?= $escaper->escapeHtmlAttr($item['width'] ?? $defaultWidth) ?>"
                    height="<?= $escaper->escapeHtmlAttr($item['height'] ?? $defaultHeight) ?>"
                    loading="lazy"
                >
            <?php endforeach; ?>
        </div>

        <?php // Fake row for CSS only marquee effect ?>
        <div aria-hidden="true" class="<?= $escaper->escapeHtmlAttr($marqueeGroupClasses) ?>">
            <?php foreach ($items as $item): ?>
                <img
                    class="h-16 w-auto object-contain"
                    style="max-width: 120px;"
                    src="<?= $escaper->escapeHtmlAttr($item['src']) ?>"
                    alt="<?= $escaper->escapeHtmlAttr($item['alt'] ?? '') ?>"
                    width="<?= $escaper->escapeHtmlAttr($item['width'] ?? $defaultWidth) ?>"
                    height="<?= $escaper->escapeHtmlAttr($item['height'] ?? $defaultHeight) ?>"
                    loading="lazy"
                >
            <?php endforeach; ?>
        </div>
    </div>

    <style>
        @keyframes marqueeScroll {
            from {
                translate: none;
            }
            to {
                translate: calc(-100% - var(--gap));
            }
        }
    </style>
</section>
