<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<script>
    if (typeof initCartTotals === 'undefined') {
        function initCartTotals() {
            return {
                totalsData: null,
                quoteData: null,
                shippingMethod: null,
                totalsSort: {"discount":"20","grand_total":"100","shipping":"30","subtotal":"10","tax":"40","weee":"35","weee_tax":"35","mollie_payment_fee":"25"},
                isLoading: false,
                wrapperClass: 'flex justify-between items-center py-2 text-gray-600',
                wrapperClassTotals: 'flex justify-between items-center py-3 text-lg font-bold text-gray-900 border-t border-gray-200 mt-2',
                init() {
                    this.totalsData = window.checkoutConfig.totalsData;
                    this.quoteData = window.checkoutConfig.quoteData;
                    this.shippingMethod = window.checkoutConfig.selectedShippingMethod;
                },
                getSortedSegments() {
                    const segments = this.totalsData.total_segments;

                    return Array.from(segments).sort((a,b) => {

                        const valueA = this.totalsSort[a.code] || 0;
                        const valueB = this.totalsSort[b.code] || 0;

                        return valueA - valueB;
                    })
                },
                getTotals() {
                    return this.totalsData
                },
                updateTotals(totalsData) {
                    this.totalsData = totalsData
                },
                updateShippingMethod(data) {
                    if (data && typeof data === 'object' && data.method) {
                        this.shippingMethod = {
                            carrier_code: data.method.split('_')[0],
                            method_code: data.method.split('_')[1],
                            method_title: data.method_title
                        };
                    } else {
                        this.shippingMethod = data;
                    }
                },
                excludingTaxMessage: '<?= $escaper->escapeJs(__('net')) ?>',
                includingTaxMessage: '<?= $escaper->escapeJs(__('gross')) ?>',
                eventListeners: {
                    ['@update-totals.window']() {
                        this.updateTotals(this.$event.detail.data)
                    },
                    ['@update-shipping-method.window']() {
                        this.updateShippingMethod(this.$event.detail);
                    },
                    ['@update-totals-start.window']() {
                        this.isLoading = true;
                    },
                    ['@update-totals-end.window']() {
                        this.isLoading = false;
                    }
                },
                formatTotalLabel() {
                    return `${this.segment.title} `;
                },
                formatTotalLabelInclTax() {
                    return `${this.segment.title} ${this.includingTaxMessage} `;
                },
                formatTotalLabelExclTax() {
                    return `${this.segment.title} ${this.excludingTaxMessage} `;
                },
            }
        }
    }
    window.addEventListener('alpine:init', () => Alpine.data('initCartTotals', initCartTotals), {once: true})
</script>

<div id="cart-totals" class="cart-totals relative bg-white border border-gray-200 rounded-lg shadow-sm p-6" x-data="initCartTotals" x-bind="eventListeners">
    <h3 class="text-lg font-bold text-gray-900 mb-4"><?= $escaper->escapeHtml(__('Summary')) ?></h3>
    <template x-if="isLoading">
        <div class="z-10 absolute inset-0 flex items-center justify-center bg-white/60 rounded-lg">
            <svg class="animate-spin h-8 w-8 text-primary" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
        </div>
    </template>
    <div class="space-y-1">
        <template x-for="(segment, index) in getSortedSegments" :key="index">
            <div>
                <div x-data="initDiscountTotalSegment">
                    <template x-if="isDiscountSegment" data-total-code="discount">
                        <div :class="wrapperClass" class="text-green-600">
                            <div x-text="formatTotalLabel"></div>
                            <div x-text="formatDiscountValue" class="font-medium"></div>
                        </div>
                    </template>
                </div>
                <!-- display subtotal excluding tax -->
                <div x-data="initGrandTotalSegment">
                    <template x-if="isGrandTotalAndIncl">
                        <div class="pt-2">
                            <div :class="wrapperClassTotals">
                                <div x-text="formatTotalLabelInclTax"></div>
                                <div x-text="formatGrandTotal" class="text-primary"></div>
                            </div>

                            <div :class="wrapperClass" class="text-sm !py-0">
                                <div x-html="formatTotalLabelExclTax"></div>
                                <div x-text="formatGrandTotalExclTax"></div>
                            </div>
                        </div>
                    </template>

                    <!-- display subtotal including tax -->
                    <template x-if="isGrandTotalAndExcl">
                        <div :class="wrapperClassTotals">
                            <div x-text="formatTotalLabel"></div>
                            <div :data-amount="segment.value" x-text="formatGrandTotal" class="text-primary"></div>
                        </div>
                    </template>
                </div>

                <div x-data="initShippingTotalSegment">
                    <!-- display shipping including and excluding tax -->
                    <template x-if="isShippingSegmentAndDisplayBoth">
                        <div class="py-2 border-b border-gray-100">
                            <div class="flex justify-between items-center text-gray-900 font-medium">
                                <div x-text="formatTotalLabelInclTax"></div>
                                <div x-text="formatShippingInclTax"></div>
                            </div>
                            <div class="flex justify-between items-center text-sm text-gray-500 mt-1">
                                <div x-text="formatTotalLabelExclTax"></div>
                                <div x-text="formatShippingAmount"></div>
                            </div>
                        </div>
                    </template>

                    <!-- display shipping excluding tax -->
                    <template x-if="isShippingSegmentAndDisplayExcl">
                        <div :class="wrapperClass">
                            <div x-text="formatTotalLabel"></div>
                            <div x-text="formatShippingTotalValue" class="font-medium text-gray-900"></div>
                        </div>
                    </template>

                    <!-- display shipping including tax -->
                    <template x-if="isShippingSegmentAndDisplayIncl">
                        <div :class="wrapperClass">
                            <div x-text="formatTotalLabel"></div>
                            <div x-text="formatShippingInclTax" class="font-medium text-gray-900"></div>
                        </div>
                    </template>
                </div>
                <!-- display subtotal including and excluding tax -->
                <div x-data="initSubtotalSegment">
                    <template x-if="isSubtotalSegmentAndDisplayBoth">
                        <div class="py-2 border-b border-gray-100">
                            <div class="flex justify-between items-center text-gray-900 font-medium">
                                <div x-html="formatTotalLabelInclTax"></div>
                                <div x-text="formatSubtotalInclTax"></div>
                            </div>
                            <div class="flex justify-between items-center text-sm text-gray-500 mt-1">
                                <div x-html="formatTotalLabelExclTax"></div>
                                <div x-text="formatSubtotal"></div>
                            </div>
                        </div>
                    </template>

                    <!-- display subtotal excluding tax -->
                    <template x-if="isSubtotalSegmentAndDisplayExcl">
                        <div :class="wrapperClass">
                            <div x-html="formatTotalLabel"></div>
                            <div x-text="formatSubtotal" class="font-medium text-gray-900"></div>
                        </div>
                    </template>

                    <!-- display subtotal including tax -->
                    <template x-if="isSubtotalSegmentAndDisplayIncl">
                        <div :class="wrapperClass">
                            <div x-html="formatTotalLabel"></div>
                            <div :data-amount="totalsData.subtotal_incl_tax" x-text="formatSubtotalInclTax" class="font-medium text-gray-900"></div>
                        </div>
                    </template>
                </div>
                <template x-if="segment.code === 'tax' &amp;&amp; (segment.value &gt; 0 || checkoutConfig.isZeroTaxDisplayed)">
                    <div>
                        <template x-if="!(segment.value &gt; 0 &amp;&amp; checkoutConfig.isFullTaxSummaryDisplayed)">
                            <div :class="wrapperClass">
                                <div x-text="segment.title"></div>
                                <div x-text="hyva.formatPrice(segment.value)" class="font-medium text-gray-900"></div>
                            </div>
                        </template>

                        <template x-if="segment.value &gt; 0 &amp;&amp; checkoutConfig.isFullTaxSummaryDisplayed">
                            <details class="group">
                                <summary class="block cursor-pointer [&amp;::-webkit-details-marker]:hidden" :class="wrapperClass">
                                    <span x-text="segment.title"></span>
                                    <span class="inline-flex items-center gap-x-1 justify-self-end font-medium text-gray-900">
                                        <span x-text="hyva.formatPrice(segment.value)"></span>
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="transform group-open:rotate-180 transition-transform" width="16" height="16" aria-hidden="true">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M19 9l-7 7-7-7"></path>
                                        </svg>
                                    </span>
                                </summary>
                                <div class="pl-4 text-sm text-gray-500 space-y-1 pb-2">
                                    <template x-for="(taxItem, index) in segment.extension_attributes.tax_grandtotal_details" :key="index">
                                        <div class="flex justify-between">
                                            <div>
                                                <template x-for="(taxRate, index) in taxItem.rates">
                                                    <div x-text="`${taxRate.title}`"></div>
                                                </template>
                                            </div>
                                            <div x-text="hyva.formatPrice(taxItem.amount)"></div>
                                        </div>
                                    </template>
                                </div>
                            </details>
                        </template>
                    </div>
                </template>
                <div x-data="initFixedProductTaxTotalSegment">
                    <template x-if="isFptSegment">
                        <div :class="wrapperClass">
                            <div x-html="formatTotalLabel"></div>
                            <div x-text="formatFptTotal" class="font-medium text-gray-900"></div>
                        </div>
                    </template>
                </div>
            </div>
        </template>
    </div>
</div>

<script>
    if (typeof initShippingTotalSegment === 'undefined') {
        function initShippingTotalSegment() {
            return {
                isShippingSegmentAndDisplayBoth() {
                    return this.segment.code === 'shipping' && this.quoteData.is_virtual === 0 && !!this.shippingMethod && 'both' === window.checkoutConfig.reviewShippingDisplayMode;
                },
                isShippingSegmentAndDisplayExcl() {
                    return this.segment.code === 'shipping' && this.quoteData.is_virtual === 0 && !!this.shippingMethod && 'excluding' === window.checkoutConfig.reviewShippingDisplayMode;
                },
                isShippingSegmentAndDisplayIncl() {
                    return this.segment.code === 'shipping' && this.quoteData.is_virtual === 0 && !!this.shippingMethod && 'including' === window.checkoutConfig.reviewShippingDisplayMode;
                },
                formatShippingTotalValue() {
                    return hyva.formatPrice(this.segment.value);
                },
                formatShippingInclTax() {
                    return hyva.formatPrice(this.totalsData.shipping_incl_tax);
                },
                formatShippingAmount() {
                    return hyva.formatPrice(this.totalsData.shipping_amount);
                },
                getShippingTitle() {
                    if (this.shippingMethod && this.shippingMethod.method_title) {
                        return '<?= $escaper->escapeJs(__('Delivery')) ?> (' + this.shippingMethod.method_title + ')';
                    }
                    return this.segment.title;
                },
                formatTotalLabelExclTax() {
                    return `${this.getShippingTitle()} ${this.excludingTaxMessage}`;
                },
                formatTotalLabelInclTax() {
                    return `${this.getShippingTitle()} ${this.includingTaxMessage}`;
                },
                formatTotalLabel() {
                    return this.getShippingTitle();
                }
            };
        }
    }
    window.addEventListener('alpine:init', () => Alpine.data('initShippingTotalSegment', initShippingTotalSegment), {once: true})
</script>

<script>
    if (typeof initSubtotalSegment === 'undefined') {
        function initSubtotalSegment() {
            return {
                isSubtotalSegmentAndDisplayBoth() {
                    return this.segment.code === 'subtotal' && 'both' === window.checkoutConfig.reviewTotalsDisplayMode;
                },
                isSubtotalSegmentAndDisplayExcl() {
                    return this.segment.code === 'subtotal' && 'excluding' === window.checkoutConfig.reviewTotalsDisplayMode
                },
                isSubtotalSegmentAndDisplayIncl() {
                    return this.segment.code === 'subtotal' && 'including' === window.checkoutConfig.reviewTotalsDisplayMode
                },
                formatTotalLabelExclTax() {
                    return '<?= $escaper->escapeJs(__('Subtotal')) ?> (<?= $escaper->escapeJs(__('net')) ?>)';
                },
                formatTotalLabelInclTax() {
                    return '<?= $escaper->escapeJs(__('Subtotal')) ?> (<?= $escaper->escapeJs(__('gross')) ?>)';
                },
                formatSubtotal() {
                    return hyva.formatPrice(this.totalsData.subtotal);
                },
                formatSubtotalInclTax() {
                    return hyva.formatPrice(this.totalsData.subtotal_incl_tax);
                },
            };
        }
    }
    window.addEventListener('alpine:init', () => Alpine.data('initSubtotalSegment', initSubtotalSegment), {once: true})
</script>

<script>
    if (typeof initGrandTotalSegment === 'undefined') {
        function initGrandTotalSegment() {
            return {
                isGrandTotalAndIncl() {
                    return this.segment.code === 'grand_total' && window.checkoutConfig.includeTaxInGrandTotal;
                },
                isGrandTotalAndExcl() {
                    return this.segment.code === 'grand_total' && !window.checkoutConfig.includeTaxInGrandTotal;
                },
                formatGrandTotal() {
                    return hyva.formatPrice(this.segment.value);
                },
                formatGrandTotalExclTax() {
                    return hyva.formatPrice(window.checkoutConfig.totalsData.grand_total - window.checkoutConfig.totalsData.tax_amount);
                },
                formatTotalLabelInclTax() {
                    return '<?= $escaper->escapeJs(__('Grand Total')) ?> (<?= $escaper->escapeJs(__('gross')) ?>)';
                },
                formatTotalLabelExclTax() {
                    return '<?= $escaper->escapeJs(__('Grand Total')) ?> (<?= $escaper->escapeJs(__('net')) ?>)';
                },
                formatTotalLabel() {
                    return '<?= $escaper->escapeJs(__('Grand Total')) ?>';
                }
            }
        }
    }
    window.addEventListener('alpine:init', () => Alpine.data('initGrandTotalSegment', initGrandTotalSegment), {once: true})
</script>

<script>
    if (typeof initDiscountTotalSegment === 'undefined') {
        function initDiscountTotalSegment() {
            return {
                isDiscountSegment() {
                    return this.segment.code === 'discount';
                },
                formatDiscountValue() {
                    return hyva.formatPrice(this.segment.value);
                }
            };
        }
    }
    window.addEventListener('alpine:init', () => Alpine.data('initDiscountTotalSegment', initDiscountTotalSegment), {once: true})
</script>

<script>
    if (typeof initTaxSegment === 'undefined') {
        function initTaxSegment() {
            return {
                taxSummaryIsOpen: false,
                isTaxSegmentVisible() {
                    return this.segment.code === 'tax' && (this.segment.value > 0 || window.checkoutConfig.isZeroTaxDisplayed);
                },
                isTaxSummaryVisible() {
                    return this.segment.value > 0 && window.checkoutConfig.isFullTaxSummaryDisplayed;
                },
                isTaxSummaryHidden() {
                    return ! this.isTaxSummaryVisible()
                },
                toggle() {
                    this.taxSummaryIsOpen = ! this.taxSummaryIsOpen;
                },
                summaryCssClasses() {
                    return {
                        'rotate-180': this.taxSummaryIsOpen
                    };
                },
                formatTaxRateLabel() {
                    return `${this.taxRate.title} (${this.taxRate.percent}%)`;
                },
                formatTaxTotal() {
                    return hyva.formatPrice(this.segment.value);
                },
                formatTaxDetailAmount() {
                    return hyva.formatPrice(this.taxItem.amount);
                }
            };
        }
    }
    window.addEventListener('alpine:init', () => Alpine.data('initTaxSegment', initTaxSegment), {once: true})
</script>

<script>
    if (typeof initFixedProductTaxTotalSegment === 'undefined') {
        function initFixedProductTaxTotalSegment() {
            return {
                isFptSegment() {
                    return this.segment.code === 'weee_tax';
                },
                formatFptTotal() {
                    return hyva.formatPrice(this.segment.value);
                }
            };
        }
    }
    window.addEventListener('alpine:init', () => Alpine.data('initFixedProductTaxTotalSegment', initFixedProductTaxTotalSegment), {once: true})
</script>
