<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<script>
    function initCartTotals() {
        return {
            totalsData: null,
            quoteData: null,
            shippingMethod: null,
            totalsSort: {"discount":"20","grand_total":"100","shipping":"30","subtotal":"10","tax":"40","weee":"35","weee_tax":"35","mollie_payment_fee":"25"},
            isLoading: false,
            wrapperClass: 'grid grid-cols-[1.5fr_1fr] md:grid-cols-2 gap-x-1 py-3 border-b border-gray-300 text-fg-secondary',
            wrapperClassTotals: 'mt-4 grid grid-cols-[1.5fr_1fr] md:grid-cols-2 gap-x-1 py-3 text-xl font-semibold',
            init() {
                this.totalsData = window.checkoutConfig.totalsData;
                this.quoteData = window.checkoutConfig.quoteData;
                this.shippingMethod = window.checkoutConfig.selectedShippingMethod;
            },
            getSortedSegments() {
                const segments = this.totalsData.total_segments;

                return Array.from(segments).sort((a,b) => {

                    const valueA = this.totalsSort[a.code] || 0;
                    const valueB = this.totalsSort[b.code] || 0;

                    return valueA - valueB;
                })
            },
            getTotals() {
                return this.totalsData
            },
            updateTotals(totalsData) {
                this.totalsData = totalsData
            },
            updateShippingMethod(shippingMethod) {
                this.shippingMethod = shippingMethod;
            },
            excludingTaxMessage: '<?= $escaper->escapeJs(__('net')) ?>',
            includingTaxMessage: '<?= $escaper->escapeJs(__('gross')) ?>',
            eventListeners: {
                ['@update-totals.window']() {
                    this.updateTotals(this.$event.detail.data)
                },
                ['@update-shipping-method.window']() {
                    this.updateShippingMethod(this.$event.detail.method);
                },
                ['@update-totals-start.window']() {
                    this.isLoading = true;
                },
                ['@update-totals-end.window']() {
                    this.isLoading = false;
                }
            },
            formatTotalLabel() {
                return `${this.segment.title} `;
            },
            formatTotalLabelInclTax() {
                return `${this.segment.title} ${this.includingTaxMessage} `;
            },
            formatTotalLabelExclTax() {
                return `${this.segment.title} ${this.excludingTaxMessage} `;
            },
        }
    }
    window.addEventListener('alpine:init', () => Alpine.data('initCartTotals', initCartTotals), {once: true})
</script>

<div id="cart-totals" class="cart-totals relative my-4" x-data="initCartTotals" x-bind="eventListeners">
    <template x-if="isLoading">
    <div class="z-10 absolute w-full h-full flex items-center justify-center bg-white/60">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 40 40" fill="currentColor" class="loader-dancers" aria-hidden="true">
    <rect x="6" y="20" width="14" height="14" rx="0"></rect>
    <rect x="20" y="20" width="14" height="14" rx="0"></rect>
</svg>
    </div>
</template>
    <template x-for="(segment, index) in getSortedSegments" :key="index">
        <div>
            <div x-data="initDiscountTotalSegment">
<template x-if="isDiscountSegment" data-total-code="discount">
    <div :class="wrapperClass">
        <div x-text="formatTotalLabel"></div>
        <div x-text="formatDiscountValue" class="justify-self-end"></div>
    </div>
</template>
</div>
<!-- display subtotal excluding tax -->
<div x-data="initGrandTotalSegment">
<template x-if="isGrandTotalAndIncl">
    <div class="divide-y">
        <div :class="wrapperClassTotals">
            <div x-text="formatTotalLabelInclTax"></div>
            <div x-text="formatGrandTotal" class="justify-self-end"></div>
        </div>

        <div :class="wrapperClass" class="text-base">
            <div x-html="formatTotalLabelExclTax"></div>
            <div x-text="formatGrandTotalExclTax" class="justify-self-end"></div>
        </div>
    </div>
</template>

<!-- display subtotal including tax -->
<template x-if="isGrandTotalAndExcl">
    <div :class="wrapperClassTotals">
        <div x-text="formatTotalLabel"></div>
        <div :data-amount="segment.value" x-text="formatGrandTotal" class="justify-self-end"></div>
    </div>
</template>
</div>

<div x-data="initShippingTotalSegment">
    <!-- display shipping including and excluding tax -->
    <template x-if="isShippingSegmentAndDisplayBoth">
        <div class="border-b border-gray-300 py-3">
            <div class="grid grid-cols-[1.5fr_1fr] md:grid-cols-2 gap-x-1">
                <div x-text="formatTotalLabelInclTax" class="font-bold text-gray-900"></div>
                <div x-text="formatShippingInclTax" class="font-bold text-gray-900 justify-self-end"></div>
            </div>
            <div class="grid grid-cols-[1.5fr_1fr] md:grid-cols-2 gap-x-1 mt-1 text-sm text-gray-500">
                <div x-text="formatTotalLabelExclTax"></div>
                <div x-text="formatShippingAmount" class="justify-self-end"></div>
            </div>
        </div>
    </template>

    <!-- display shipping excluding tax -->
    <template x-if="isShippingSegmentAndDisplayExcl">
        <div :class="wrapperClass">
            <div x-text="formatTotalLabel"></div>
            <div x-text="formatShippingTotalValue" class="justify-self-end"></div>
        </div>
    </template>

    <!-- display shipping including tax -->
    <template x-if="isShippingSegmentAndDisplayIncl">
        <div :class="wrapperClass">
            <div x-text="formatTotalLabel"></div>
            <div x-text="formatShippingInclTax" class="justify-self-end"></div>
        </div>
    </template>
</div>
<!-- display subtotal including and excluding tax -->
<div x-data="initSubtotalSegment">
<template x-if="isSubtotalSegmentAndDisplayBoth">
    <div class="border-b border-gray-300 py-3">
        <div class="grid grid-cols-[1.5fr_1fr] md:grid-cols-2 gap-x-1">
            <div x-html="formatTotalLabelInclTax" class="font-bold text-gray-900"></div>
            <div x-text="formatSubtotalInclTax" class="font-bold text-gray-900 justify-self-end"></div>
        </div>
        <div class="grid grid-cols-[1.5fr_1fr] md:grid-cols-2 gap-x-1 mt-1 text-sm text-gray-500">
            <div x-html="formatTotalLabelExclTax"></div>
            <div x-text="formatSubtotal" class="justify-self-end"></div>
        </div>
    </div>
</template>

<!-- display subtotal excluding tax -->
<template x-if="isSubtotalSegmentAndDisplayExcl">
    <div :class="wrapperClass">
        <div x-html="formatTotalLabel"></div>
        <div x-text="formatSubtotal" class="justify-self-end"></div>
    </div>
</template>

<!-- display subtotal including tax -->
<template x-if="isSubtotalSegmentAndDisplayIncl">
    <div :class="wrapperClass">
        <div x-html="formatTotalLabel"></div>
        <div :data-amount="totalsData.subtotal_incl_tax" x-text="formatSubtotalInclTax" class="justify-self-end"></div>
    </div>
</template>
</div>
<template x-if="segment.code === 'tax' &amp;&amp; (segment.value &gt; 0 || checkoutConfig.isZeroTaxDisplayed)">
    <div>
        <template x-if="!(segment.value &gt; 0 &amp;&amp; checkoutConfig.isFullTaxSummaryDisplayed)">
            <div :class="wrapperClass">
                <div x-text="segment.title"></div>
                <div x-text="hyva.formatPrice(segment.value)" class="justify-self-end"></div>
            </div>
        </template>

        <template x-if="segment.value &gt; 0 &amp;&amp; checkoutConfig.isFullTaxSummaryDisplayed">
            <details class="group">
                <summary class="block cursor-pointer [&amp;::-webkit-details-marker]:hidden" :class="wrapperClass">
                    <span x-text="segment.title"></span>
                    <span class="inline-flex items-center gap-x-1 justify-self-end">
                        <span x-text="hyva.formatPrice(segment.value)"></span>
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="transform group-open:rotate-180" width="18" height="18" aria-hidden="true">
  <path stroke-linecap="round" stroke-linejoin="round" d="M19 9l-7 7-7-7"></path>
</svg>
                    </span>
                </summary>
                <template x-for="(taxItem, index) in segment.extension_attributes.tax_grandtotal_details" :key="index">
                    <div :class="wrapperClass">
                        <div>
                            <template x-for="(taxRate, index) in taxItem.rates">
                                <div x-text="`${taxRate.title}`"></div>
                            </template>
                        </div>
                        <div x-text="hyva.formatPrice(taxItem.amount)" class="justify-self-end"></div>
                    </div>
                </template>

        </details></template>
    </div>
</template>
<div x-data="initFixedProductTaxTotalSegment">
<template x-if="isFptSegment">
    <div :class="wrapperClass">
        <div x-html="formatTotalLabel"></div>
        <div x-text="formatFptTotal" class="justify-self-end"></div>
    </div>
</template>
</div>
        </div>
    </template>
</div>

<script>
    function initShippingTotalSegment() {
        return {
            isShippingSegmentAndDisplayBoth() {
                return this.segment.code === 'shipping' && this.quoteData.is_virtual === 0 && !!this.shippingMethod && 'both' === window.checkoutConfig.reviewShippingDisplayMode;
            },
            isShippingSegmentAndDisplayExcl() {
                return this.segment.code === 'shipping' && this.quoteData.is_virtual === 0 && !!this.shippingMethod && 'excluding' === window.checkoutConfig.reviewShippingDisplayMode;
            },
            isShippingSegmentAndDisplayIncl() {
                return this.segment.code === 'shipping' && this.quoteData.is_virtual === 0 && !!this.shippingMethod && 'including' === window.checkoutConfig.reviewShippingDisplayMode;
            },
            formatShippingTotalValue() {
                return hyva.formatPrice(this.segment.value);
            },
            formatShippingInclTax() {
                return hyva.formatPrice(this.totalsData.shipping_incl_tax);
            },
            formatShippingAmount() {
                return hyva.formatPrice(this.totalsData.shipping_amount);
            },
            formatTotalLabelExclTax() {
                return '<?= $escaper->escapeJs(__('Delivery')) ?> (<?= $escaper->escapeJs(__('net')) ?>)';
            },
            formatTotalLabelInclTax() {
                return '<?= $escaper->escapeJs(__('Delivery')) ?> (<?= $escaper->escapeJs(__('gross')) ?>)';
            },
            formatTotalLabel() {
                return '<?= $escaper->escapeJs(__('Delivery')) ?>';
            }
        };
    }
    window.addEventListener('alpine:init', () => Alpine.data('initShippingTotalSegment', initShippingTotalSegment), {once: true})
</script>

<script>
    function initSubtotalSegment() {
        return {
            isSubtotalSegmentAndDisplayBoth() {
                return this.segment.code === 'subtotal' && 'both' === window.checkoutConfig.reviewTotalsDisplayMode;
            },
            isSubtotalSegmentAndDisplayExcl() {
                return this.segment.code === 'subtotal' && 'excluding' === window.checkoutConfig.reviewTotalsDisplayMode
            },
            isSubtotalSegmentAndDisplayIncl() {
                return this.segment.code === 'subtotal' && 'including' === window.checkoutConfig.reviewTotalsDisplayMode
            },
            formatTotalLabelExclTax() {
                return '<?= $escaper->escapeJs(__('Subtotal')) ?> (<?= $escaper->escapeJs(__('net')) ?>)';
            },
            formatTotalLabelInclTax() {
                return '<?= $escaper->escapeJs(__('Subtotal')) ?> (<?= $escaper->escapeJs(__('gross')) ?>)';
            },
            formatSubtotal() {
                return hyva.formatPrice(this.totalsData.subtotal);
            },
            formatSubtotalInclTax() {
                return hyva.formatPrice(this.totalsData.subtotal_incl_tax);
            },
        };
    }
    window.addEventListener('alpine:init', () => Alpine.data('initSubtotalSegment', initSubtotalSegment), {once: true})
</script>

<script>
    function initGrandTotalSegment() {
        return {
            isGrandTotalAndIncl() {
                return this.segment.code === 'grand_total' && window.checkoutConfig.includeTaxInGrandTotal;
            },
            isGrandTotalAndExcl() {
                return this.segment.code === 'grand_total' && !window.checkoutConfig.includeTaxInGrandTotal;
            },
            formatGrandTotal() {
                return hyva.formatPrice(this.segment.value);
            },
            formatGrandTotalExclTax() {
                return hyva.formatPrice(window.checkoutConfig.totalsData.grand_total - window.checkoutConfig.totalsData.tax_amount);
            },
            formatTotalLabelInclTax() {
                return '<?= $escaper->escapeJs(__('Grand Total')) ?> (<?= $escaper->escapeJs(__('gross')) ?>)';
            },
            formatTotalLabelExclTax() {
                return '<?= $escaper->escapeJs(__('Grand Total')) ?> (<?= $escaper->escapeJs(__('net')) ?>)';
            },
            formatTotalLabel() {
                return '<?= $escaper->escapeJs(__('Grand Total')) ?>';
            }
        }
    }
    window.addEventListener('alpine:init', () => Alpine.data('initGrandTotalSegment', initGrandTotalSegment), {once: true})
</script>

<script>
    function initDiscountTotalSegment() {
        return {
            isDiscountSegment() {
                return this.segment.code === 'discount';
            },
            formatDiscountValue() {
                return hyva.formatPrice(this.segment.value);
            }
        };
    }
    window.addEventListener('alpine:init', () => Alpine.data('initDiscountTotalSegment', initDiscountTotalSegment), {once: true})
</script>

<script>
    function initTaxSegment() {
        return {
            taxSummaryIsOpen: false,
            isTaxSegmentVisible() {
                return this.segment.code === 'tax' && (this.segment.value > 0 || window.checkoutConfig.isZeroTaxDisplayed);
            },
            isTaxSummaryVisible() {
                return this.segment.value > 0 && window.checkoutConfig.isFullTaxSummaryDisplayed;
            },
            isTaxSummaryHidden() {
                return ! this.isTaxSummaryVisible()
            },
            toggle() {
                this.taxSummaryIsOpen = ! this.taxSummaryIsOpen;
            },
            summaryCssClasses() {
                return {
                    'rotate-180': this.taxSummaryIsOpen
                };
            },
            formatTaxRateLabel() {
                return `${this.taxRate.title} (${this.taxRate.percent}%)`;
            },
            formatTaxTotal() {
                return hyva.formatPrice(this.segment.value);
            },
            formatTaxDetailAmount() {
                return hyva.formatPrice(this.taxItem.amount);
            }
        };
    }
    window.addEventListener('alpine:init', () => Alpine.data('initTaxSegment', initTaxSegment), {once: true})
</script>

<script>
    function initFixedProductTaxTotalSegment() {
        return {
            isFptSegment() {
                return this.segment.code === 'weee_tax';
            },
            formatFptTotal() {
                return hyva.formatPrice(this.segment.value);
            }
        };
    }
    window.addEventListener('alpine:init', () => Alpine.data('initFixedProductTaxTotalSegment', initFixedProductTaxTotalSegment), {once: true})
</script>
