<?php
/** @var Template $block */

// 1. Pobieramy Object Managera (w phtml to najszybsza metoda na skróty)
use Magento\Framework\App\ObjectManager;
use Magento\Framework\View\Element\Template;

$om = ObjectManager::getInstance();

// 2. Pobieramy repozytorium zasobów
$assetRepository = $om->get('\Magento\Framework\View\Asset\Repository');

// 3. Tworzymy asset dla Twojego pliku CSS (tu wpisz ścieżkę ID pliku)
// Zazwyczaj jest to 'css/styles.css' lub 'Magento_Theme::css/styles.css'
$asset = $assetRepository->createAsset('css/styles.css');
// 4. Pobieramy ścieżkę fizyczną na dysku
$sourceFile = $asset->getSourceFile();
$content = '';
if (file_exists($sourceFile)) {
    $content = file_get_contents($sourceFile);
}

//$font = $assetRepository->createAsset('css/font-awesome.css');
// 4. Pobieramy ścieżkę fizyczną na dysku
//$sourceFileFont = $font->getSourceFile();
$contentFont = '';
/*if (file_exists($sourceFileFont)) {
    $contentFont = file_get_contents($sourceFileFont);
}*/
?>

<?php if ($content): ?>
    <style>
        <?= /* @noEscape */ $content; ?>
    </style>
<?php endif; ?>
<?php if ($contentFont): ?>
    <style>
        <?= /* @noEscape */ $contentFont; ?>
    </style>
<?php endif; ?>

