<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Store;
use Hyva\Theme\ViewModel\Logo\LogoSizeResolver;
use Hyva\Theme\ViewModel\Logo\LogoPathResolver;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Framework\Escaper;
use Magento\Theme\Block\Html\Header\Logo;

/** @var Logo $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var StoreConfig $storeConfig */
$storeConfig = $viewModels->require(StoreConfig::class);
$storeName = $storeConfig->getStoreConfig('general/store_information/name') ?: $block->getThemeName() ?: __('Store logo');

/** @var LogoSizeResolver $logoSizeResolver */
$logoSizeResolver = $viewModels->require(LogoSizeResolver::class);
$logoWidth = $logoSizeResolver && $logoSizeResolver->getWidth()
    ? $logoSizeResolver->getWidth()
    : ($block->getLogoWidth() ?: 200);
$logoHeight = $logoSizeResolver && $logoSizeResolver->getHeight()
    ? $logoSizeResolver->getHeight()
    : ($block->getLogoHeight() ?: 150);

/** @var Store $store */
$store = $viewModels->require(Store::class);
$storeCode = $store->getStoreCode();
$logoSrc = "https://pub.gardenlawn.pl/media/images/logo.webp";
$logoWidth = 200;
$logoHeight = 60.1;
switch ($storeCode) {
    case 'amrobots':
        $logoSrc = "https://pub.am-robots.pl/media/producers/am-robots.webp";
        $logoWidth = 200;
        $logoHeight = 72.9;
        break;
    case 'finnpolska':
        $logoSrc = "https://pub.finnpolska.pl/media/producers/finn.webp";
        $logoWidth = 200;
        $logoHeight = 61.9;
        break;
}
?>

<a
    class="inline-block align-middle"
    href="<?= $escaper->escapeUrl($block->getUrl()) ?>"
    title="<?= $escaper->escapeHtmlAttr(__('Go to Home page')) ?>"
>
    <?php if ($logoSrc): ?>
        <img
            class="hidden lg:block"
            src="<?= $escaper->escapeUrl($logoSrc) ?>"
            alt="<?= $escaper->escapeHtmlAttr($block->getLogoAlt() ?: $storeName) ?>"
            width="<?= $escaper->escapeHtmlAttr($logoWidth) ?>"
            height="<?= $escaper->escapeHtmlAttr($logoHeight) ?>"
            loading="lazy"
            fetchpriority="high"
        >
    <?php else: ?>
        <span class="text-xl font-medium font-title">
            <?= $escaper->escapeHtml($storeName) ?>
        </span>
    <?php endif; ?>
</a>
