<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Customer\Block\Widget\Company;
use Magento\Customer\Helper\Address as AddressHelper;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var Escaper $escaper */
/** @var Company $block */
/** @var Template $this */

$validationClass = $this->helper(AddressHelper::class)->getAttributeValidationClass('company');
$disabled = $block->getDisabled();

?>
<div class="field field-reserved company <?= $block->isRequired() ? 'required' : '' ?>">
    <label for="company" class="label">
        <span><?= $escaper->escapeHtml(__('Company')) ?></span>
    </label>
    <div class="control">
        <input type="text"
               name="company"
               id="company"
               <?php if ($block->isRequired()): ?>
                   required
               <?php endif; ?>
               value="<?= $escaper->escapeHtmlAttr($block->getCompany()) ?>"
               title="<?= $escaper->escapeHtmlAttr(__('Company')) ?>"
               class="form-input w-full <?= $escaper->escapeHtmlAttr($validationClass) ?>"
            <?= $disabled ? 'disabled' : '' ?>
         >
    </div>
</div>
