<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Customer\Block\Widget\Company as CompanyWidget;
use Magento\Framework\Escaper;

/** @var CompanyWidget $block */
/** @var Escaper $escaper */

$isDisabled = $block->getData('disabled');
?>
<div class="field field-company <?= $block->isRequired() ? 'required' : '' ?>">
    <label class="label" for="<?= $escaper->escapeHtmlAttr($block->getFieldId('company')) ?>">
        <span><?= $escaper->escapeHtml($block->getStoreLabel('company')) ?></span>
    </label>
    <div class="control">
        <input type="text"
               id="<?= $escaper->escapeHtmlAttr($block->getFieldId('company')) ?>"
               name="<?= $escaper->escapeHtmlAttr($block->getFieldName('company')) ?>"
               value="<?= $escaper->escapeHtmlAttr($block->getCompany()) ?>"
               title="<?= $escaper->escapeHtmlAttr($block->getStoreLabel('company')) ?>"
               class="form-input input-text"
            <?= $block->isRequired() ? 'required' : '' ?>
            <?= $isDisabled ? 'readonly' : '' ?>
        >
    </div>
</div>
