<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Customer\Block\Widget\Name;
use Magento\Framework\Escaper;
use GardenLawn\Company\Helper\Data as CompanyHelper;
use Magento\Framework\View\Element\Template;

/** @var Name $block */
/** @var Escaper $escaper */
/** @var Template $this */

$prefix = $block->showPrefix();
$middle = $block->showMiddlename();
$suffix = $block->showSuffix();

$companyHelper = $this->helper(CompanyHelper::class);
$isB2bCustomer = in_array($companyHelper->getCurrentCustomerGroupId(), $companyHelper->getB2bCustomerGroups());
$address = $block->getObject();
$isDefaultBilling = $address && method_exists($address, 'isDefaultBilling') && $address->isDefaultBilling();
$disabled = $isB2bCustomer && $isDefaultBilling;
?>
<?php if ($prefix): ?>
    <div class="field field-reserved w-full field-name-prefix<?= $block->isPrefixRequired() ? ' required' : '' ?>">
        <label class="label" for="<?= $escaper->escapeHtmlAttr($block->getFieldId('prefix')) ?>">
            <span><?= $escaper->escapeHtml($block->getStoreLabel('prefix')) ?></span>
        </label>
        <div class="control">
            <?php if ($block->getPrefixOptions() === false): ?>
                <input type="text" id="<?= $escaper->escapeHtmlAttr($block->getFieldId('prefix')) ?>"
                       name="<?= $escaper->escapeHtmlAttr($block->getFieldName('prefix')) ?>"
                       <?= $block->isPrefixRequired() ? ' required' : '' ?>
                       value="<?= $escaper->escapeHtmlAttr($block->getObject()->getPrefix()) ?>"
                       title="<?= $escaper->escapeHtmlAttr($block->getStoreLabel('prefix')) ?>"
                       class="form-input w-full
                          <?= $escaper->escapeHtmlAttr($block->getAttributeValidationClass('prefix')) ?>"
                        <?= $block->isPrefixRequired() ? ' required' : '' ?>
                    <?= $disabled ? 'disabled' : '' ?>
                >
            <?php else: ?>
                <select id="<?= $escaper->escapeHtmlAttr($block->getFieldId('prefix')) ?>"
                        name="<?= $escaper->escapeHtmlAttr($block->getFieldName('prefix')) ?>"
                        <?= $block->isPrefixRequired() ? ' required' : '' ?>
                        title="<?= $escaper->escapeHtmlAttr($block->getStoreLabel('prefix')) ?>"
                        class="form-select <?= $escaper->escapeHtmlAttr($block->getAttributeValidationClass('prefix')) ?>"
                        <?= $block->isPrefixRequired() ? ' required' : '' ?>
                    <?= $disabled ? 'disabled' : '' ?>
                >
                    <?php foreach ($block->getPrefixOptions() as $option): ?>
                        <option value="<?= $escaper->escapeHtmlAttr($option) ?>"
                            <?php if ($block->getObject()->getPrefix() == $option): ?>
                                selected="selected"
                            <?php endif; ?>>
                            <?= $escaper->escapeHtml(__($option)) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
    <div class="field field-reserved w-full field-name-firstname required">
        <label class="label" for="<?= $escaper->escapeHtmlAttr($block->getFieldId('firstname')) ?>">
            <span>
                <?= $escaper->escapeHtml($block->getStoreLabel('firstname')) ?>
            </span>
        </label>
        <div class="control">
            <input type="text" id="<?= $escaper->escapeHtmlAttr($block->getFieldId('firstname')) ?>"
                   name="<?= $escaper->escapeHtmlAttr($block->getFieldName('firstname')) ?>"
                   value="<?= $escaper->escapeHtmlAttr($block->getObject()->getFirstname()) ?>"
                   required
                   title="<?= $escaper->escapeHtmlAttr($block->getStoreLabel('firstname')) ?>"
                   class="form-input w-full <?= $escaper->escapeHtmlAttr(
                       $block->getAttributeValidationClass('firstname')
                   ) ?>"
                   @input.debounce="onChange"
                <?= ($block->getAttributeValidationClass('firstname') == 'required-entry') ? ' required' : '' ?>
                <?= $disabled ? 'disabled' : '' ?>
            >
        </div>
    </div>
<?php if ($middle): ?>
    <?php $isMiddlenameRequired = $block->isMiddlenameRequired(); ?>
    <div class="field field-reserved w-full field-name-middlename<?= $isMiddlenameRequired ? ' required' : '' ?>">
        <label class="label" for="<?= $escaper->escapeHtmlAttr($block->getFieldId('middlename')) ?>">
            <span>
                <?= $escaper->escapeHtml($block->getStoreLabel('middlename')) ?>
            </span>
        </label>
        <div class="control">
            <input type="text" id="<?= $escaper->escapeHtmlAttr($block->getFieldId('middlename')) ?>"
                   name="<?= $escaper->escapeHtmlAttr($block->getFieldName('middlename')) ?>"
                   value="<?= $escaper->escapeHtmlAttr($block->getObject()->getMiddlename()) ?>"
                   title="<?= $escaper->escapeHtmlAttr($block->getStoreLabel('middlename')) ?>"
                   class="form-input w-full
                     <?= $escaper->escapeHtmlAttr($block->getAttributeValidationClass('middlename')) ?>"
                   @input.debounce="onChange"
                   <?= $isMiddlenameRequired ? ' required' : '' ?>
                   <?= $disabled ? 'disabled' : '' ?>
            >
        </div>
    </div>
<?php endif; ?>
    <div class="field field-reserved w-full field-name-lastname required">
        <label class="label" for="<?= $escaper->escapeHtmlAttr($block->getFieldId('lastname')) ?>">
            <span>
                <?= $escaper->escapeHtml($block->getStoreLabel('lastname')) ?>
            </span>
        </label>
        <div class="control">
            <input type="text" id="<?= $escaper->escapeHtmlAttr($block->getFieldId('lastname')) ?>"
                   name="<?= $escaper->escapeHtmlAttr($block->getFieldName('lastname')) ?>"
                   required
                   value="<?= $escaper->escapeHtmlAttr($block->getObject()->getLastname()) ?>"
                   title="<?= $escaper->escapeHtmlAttr($block->getStoreLabel('lastname')) ?>"
                   class="form-input w-full <?= $escaper->escapeHtmlAttr(
                       $block->getAttributeValidationClass('lastname')
                   ) ?>"
                   @input.debounce="onChange"
                <?= ($block->getAttributeValidationClass('lastname') == 'required-entry') ? ' required' : '' ?>
                <?= $disabled ? 'disabled' : '' ?>
            >
        </div>
    </div>
<?php if ($suffix): ?>
    <div class="field field-reserved w-full field-name-suffix<?= $block->isSuffixRequired() ? ' required' : '' ?>">
        <label class="label" for="<?= $escaper->escapeHtmlAttr($block->getFieldId('suffix')) ?>">
            <span>
                <?= $escaper->escapeHtml($block->getStoreLabel('suffix')) ?>
            </span>
        </label>
        <div class="control">
            <?php if ($block->getSuffixOptions() === false): ?>
                <input type="text" id="<?= $escaper->escapeHtmlAttr($block->getFieldId('suffix')) ?>"
                       name="<?= $escaper->escapeHtmlAttr($block->getFieldName('suffix')) ?>"
                       value="<?= $escaper->escapeHtmlAttr($block->getObject()->getSuffix()) ?>"
                       title="<?= $escaper->escapeHtmlAttr($block->getStoreLabel('suffix')) ?>"
                       class="form-input w-full
                        <?= $escaper->escapeHtmlAttr($block->getAttributeValidationClass('suffix')) ?>"
                    <?= $block->isSuffixRequired() ? ' required' : '' ?>
                    <?= $disabled ? 'disabled' : '' ?>
                >
            <?php else: ?>
                <select id="<?= $escaper->escapeHtmlAttr($block->getFieldId('suffix')) ?>"
                        name="<?= $escaper->escapeHtmlAttr($block->getFieldName('suffix')) ?>"
                        title="<?= $escaper->escapeHtmlAttr($block->getStoreLabel('suffix')) ?>"
                        class="<?= $escaper->escapeHtmlAttr($block->getAttributeValidationClass('suffix')) ?>"
                    <?= $block->isSuffixRequired() ? ' required' : '' ?>
                    <?= $disabled ? 'disabled' : '' ?>
                >
                    <?php foreach ($block->getSuffixOptions() as $option): ?>
                        <option value="<?= $escaper->escapeHtmlAttr($option) ?>"
                            <?php if ($block->getObject()->getSuffix() == $option): ?>
                                selected="selected"
                            <?php endif; ?>
                        >
                            <?= $escaper->escapeHtml(__($option)) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
