<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Customer\Block\Widget\Taxvat as TaxvatWidget;
use Magento\Framework\Escaper;

/** @var TaxvatWidget $block */
/** @var Escaper $escaper */

$isDisabled = $block->getData('disabled');
?>
<?php if ($isDisabled): ?>
    <input
        type="hidden"
        id="<?= $escaper->escapeHtmlAttr($block->getFieldId('taxvat')) ?>"
        name="<?= $escaper->escapeHtmlAttr($block->getFieldName('taxvat')) ?>"
        value="<?= $escaper->escapeHtmlAttr($block->getTaxvat()) ?>"
    >
<?php else: ?>
    <div class="w-full">
        <div class="field field-taxvat-vat-id <?= $block->isRequired() ? 'required' : '' ?>">
            <label class="label" for="<?= $escaper->escapeHtmlAttr($block->getFieldId('taxvat')) ?>">
                <span><?= $escaper->escapeHtml($block->getStoreLabel('taxvat')) ?></span>
            </label>
            <div class="control">
                <input
                    type="text"
                    id="<?= $escaper->escapeHtmlAttr($block->getFieldId('taxvat')) ?>"
                    name="<?= $escaper->escapeHtmlAttr($block->getFieldName('taxvat')) ?>"
                    value="<?= $escaper->escapeHtmlAttr($block->getTaxvat()) ?>"
                    title="<?= $escaper->escapeHtmlAttr($block->getStoreLabel('taxvat')) ?>"
                    class="form-input input-text"
                    <?= $block->isRequired() ? 'required' : '' ?>
                >
            </div>
        </div>
    </div>
<?php endif ?>
