<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$blockId = (string) $block->getBlockId() ?: $block->getNameInLayout() ?: uniqid();
$title = (string) $block->getTitle() ?: __("Details");
$open = (bool) $block->getOpen() ? 'true' : 'false';
?>

<?php if ($childrenHtml = $block->getChildHtml()): ?>
    <div
        x-data="mobileFooterCollpase"
        x-bind="eventListeners"
        class="border-b border-gray-100 lg:border-b-0 last:border-b-0"
        data-open="<?= /** @noEscape */ $open ?>"
    >
        <div
            class="group flex w-full items-center justify-between py-4 lg:py-0 gap-2 cursor-pointer lg:cursor-default select-none lg:select-auto"
            data-id="<?= $blockId ?>"
            x-bind="setToggleRoles"
            @click="toggle"
            @keyup.enter="toggle"
            @keyup.space="toggle"
        >
            <h3 class="font-bold text-gray-900 text-lg lg:mb-4"><?= $escaper->escapeHtml($title); ?></h3>
            <span
                class="transition-transform duration-300 group-aria-expanded:rotate-180 lg:hidden text-gray-400"
                x-ref="toggleIcon"
            >
                <?= $heroiconsSolid->chevronDownHtml('', 20, 20, ["aria-hidden" => 'true']); ?>
            </span>
        </div>
        <div
            id="<?= $blockId ?>"
            class="aria-[hidden=true]:hidden lg:block overflow-hidden transition-all duration-300 ease-in-out"
            x-bind="setCollapseRoles"
            x-show="isOpen"
            x-transition:enter="transition ease-out duration-200"
            x-transition:enter-start="opacity-0 -translate-y-2"
            x-transition:enter-end="opacity-100 translate-y-0"
        >
            <div class="pt-2 pb-6 lg:pt-0 lg:pb-0">
                <?= /** @noEscape */ $childrenHtml ?>
            </div>
        </div>
    </div>
<?php endif; ?>
