<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Theme\Block\Html\Footer;

/** @var Footer $block */
/** @var Escaper $escaper */
?>
<small class="flex items-center justify-center w-full vw-full py-2 bg-gray-600">
    <span class="text-white">Copyright © 2023-<?= date("Y"); ?> Garden Lawn & Irrigation</span>
</small>
