<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Customer;
use Hyva\Theme\ViewModel\StoreConfig;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var Customer $customer */
$customer = $viewModels->require(Customer::class);
/** @var StoreConfig $storeConfig */
$storeConfig = $viewModels->require(StoreConfig::class);

?>

<nav aria-label="<?= $escaper->escapeUrl($escaper->escapeHtmlAttr('Company')) ?>">
    <ul>
        <li>
            <a href="/" class="block py-1.5 hover:underline">
                <?= __("About Us") ?>
            </a>
        </li>
        <li>
            <a href="<?= $escaper->escapeUrl($block->getUrl('mapa-strony')) ?>"
               class="block py-1.5 hover:underline">
                <?= $escaper->escapeHtml(__('Site Map')) ?>
            </a>
        </li>
        <?php if ($storeConfig->getStoreConfig('catalog/seo/search_terms')): ?>
            <li>
                <a href="<?= $escaper->escapeUrl($block->getUrl('wyszukiwane-frazy')) ?>"
                   class="block py-1.5 hover:underline">
                    <?= $escaper->escapeHtml(__('Search Terms')) ?>
                </a>
            </li>
        <?php endif; ?>
    </ul>
</nav>
