<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
?>

<nav aria-label="<?= $escaper->escapeUrl($escaper->escapeHtmlAttr('Shop')) ?>">
    <ul>
        <li>
            <a
                href="<?= $escaper->escapeUrl($block->getUrl('https://am-robots.pl/kosiarki-roboty')) ?>"
                class="block py-1.5 hover:underline"
            ><?= $escaper->escapeHtml(__('Roboty koszące')) ?></a>
        </li>
        <li>
            <a
                href="<?= $escaper->escapeUrl($block->getUrl('https://am-robots.pl/garaze')) ?>"
                class="block py-1.5 hover:underline"
            ><?= $escaper->escapeHtml(__('Garaże dla robotów')) ?></a>
        </li>
        <li>
            <a
                href="<?= $escaper->escapeUrl($block->getUrl('https://am-robots.pl/noze')) ?>"
                class="block py-1.5 hover:underline"
            ><?= $escaper->escapeHtml(__('Noże do robotów koszacych')) ?></a>
        </li>
        <li>
            <a
                href="<?= $escaper->escapeUrl($block->getUrl('https://gardenlawn.pl/sprzedaz-trawy-w-rolce/trawa-w-rolce')) ?>"
                class="block py-1.5 hover:underline"
            ><?= $escaper->escapeHtml(__('Trawa w rolce')) ?></a>
        </li>
    </ul>
</nav>
