<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
?>

<nav aria-label="<?= $escaper->escapeUrl($escaper->escapeHtmlAttr('Customer Services')) ?>">
    <ul>
        <li>
            <a href="<?= $escaper->escapeUrl($block->getUrl('kontakt')) ?>"
               class="block py-1.5 hover:underline">
                <?= $escaper->escapeHtml(__('Contact')) ?>
            </a>
        </li>
        <li>
            <a href="<?= $escaper->escapeUrl($block->getUrl('zamowienia-i-zwroty')) ?>"
               class="block py-1.5 hover:underline">
                <?= $escaper->escapeHtml(__('Orders and Returns')) ?>
            </a>
        </li>
        <li>
            <a href="<?= $escaper->escapeUrl($block->getUrl('regulamin')) ?>"
                class="block py-1.5 hover:underline"
            ><?= $escaper->escapeHtml(__('Terms & Conditions')) ?></a>
        </li>
        <li>
            <a href="<?= $escaper->escapeUrl($block->getUrl('polityka-prywatnosci')) ?>"
                class="block py-1.5 hover:underline"
            ><?= $escaper->escapeHtml(__('Privacy Policy')) ?></a>
        </li>
    </ul>
</nav>
