<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
?>

<ul>
    <li>
        <a
            href="/polityka-prywatnosci"
            class="block py-1.5 hover:underline"
        ><?= $escaper->escapeHtml(__('Privacy and Cookie Policy')) ?></a>
    </li>
    <li>
        <a
            href="/regulamin"
            class="block py-1.5 hover:underline"
        ><?= $escaper->escapeHtml(__('Terms & Conditions')) ?></a>
    </li>
</ul>
