<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\PaymentIcons\ViewModel\PaymentIconsLight;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var PaymentIconsLight $paymentIcons */
$paymentIcons = $viewModels->require(PaymentIconsLight::class);

$paymentIconsWidth = 48;
$paymentIconsHeight = 32;
?>
<div
    class="container flex gap-8 flex-wrap justify-center"
    aria-label="<?= $escaper->escapeHtml(__('Payment Providers')) ?>"
>
    <div class="w-full flex justify-center">
        <picture>
            <source media="(max-width: 767px)"
                    srcset="<?php echo $block->getViewFileUrl('GardenLawn_Hyvatheme::images/PayNow/PayNow.png'); ?>">
            <source media="(min-width: 768px)"
                    srcset="<?php echo $block->getViewFileUrl('GardenLawn_Hyvatheme::images/PayNow/PayNowBanner.png'); ?>">
            <img style="max-height: 150px;"
                src="<?php echo $block->getViewFileUrl('GardenLawn_Hyvatheme::images/PayNow/PayNowBanner.png'); ?>"
                alt="PayNow"/>
        </picture>
    </div>
    <img style="height: 40px; margin-top: 20px;"
         src="<?php echo $block->getViewFileUrl('GardenLawn_Hyvatheme::images/PayNow/PayPo.svg'); ?>" alt="PayPo"/>
    <img style="height: 40px; margin-top: 20px;"
         src="<?php echo $block->getViewFileUrl('GardenLawn_Hyvatheme::images/E-Raty/e-raty.svg'); ?>"
         alt="E-Raty"/>
    <img style="height: 70px;"
         src="<?php echo $block->getViewFileUrl('GardenLawn_Hyvatheme::images/InPost/InPostPay.svg'); ?>"
         alt="InPost"/>
    <img style="height: 70px;"
         src="<?php echo $block->getViewFileUrl('GardenLawn_Hyvatheme::images/InPost/InPost.png'); ?>"
         alt="InPost"/>
</div>
