<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\PaymentIcons\ViewModel\PaymentIconsLight;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var PaymentIconsLight $paymentIcons */
$paymentIcons = $viewModels->require(PaymentIconsLight::class);

$paymentIconsWidth = 48;
$paymentIconsHeight = 32;
?>
<div
    class="container flex gap-8 flex-wrap justify-center"
    aria-label="<?= $escaper->escapeHtml(__('Payment Providers')) ?>"
>
    <div class="w-full flex justify-center">
        <picture>
            <source media="(max-width: 767px)"
                    srcset="https://pub.gardenlawn.pl/media/images/PayNow/PayNow.webp">
            <source media="(min-width: 768px)"
                    srcset="https://pub.gardenlawn.pl/media/images/PayNow/PayNowBanner.webp">
            <img style="max-height: 150px;"
                 src="https://pub.gardenlawn.pl/media/images/PayNow/PayNowBanner.webp"
                 loading="lazy"
                 alt="PayNow"/>
        </picture>
    </div>
    <img style="height: 40px; margin-top: 20px;"
         src="https://pub.gardenlawn.pl/media/images/PayNow/PayPo.svg"
         loading="lazy" alt="PayPo"/>
    <img style="height: 40px; margin-top: 20px;"
         src="https://pub.gardenlawn.pl/media/images/E-Raty/e-raty.svg"
         loading="lazy"
         alt="E-Raty"/>
    <img style="height: 70px;"
         src="https://pub.gardenlawn.pl/media/images/InPost/InPostPay.svg"
         loading="lazy"
         alt="InPost"/>
    <img style="height: 70px;"
         src="https://pub.gardenlawn.pl/media/images/InPost/InPost.webp"
         loading="lazy"
         alt="InPost"/>
</div>
