<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>

<div class="pt-2 pb-4 px-6 flex flex-col gap-2">
    <a
        href="<?= $escaper->escapeUrl($block->getUrl('checkout/cart/index')) ?>"
        class="btn btn-primary w-full justify-center"
    >
        <?= $heroicons->shoppingCartHtml('shrink-0', 20, 20, ['aria-hidden' => 'true']); ?>
        <?= $escaper->escapeHtml(__('Shopping Cart')) ?>
    </a>
    <a
        href="<?= $escaper->escapeUrl($block->getUrl('wishlist')) ?>"
        class="btn btn-secondary w-full justify-center"
    >
        <?= $heroicons->heartHtml('shrink-0', 20, 20, ['aria-hidden' => 'true']); ?>
        <?= $escaper->escapeHtml(__('My Wish List')) ?>
    </a>
    <a
        href="<?= $escaper->escapeUrl($block->getUrl('catalog/product_compare/index')) ?>"
        class="btn btn-secondary w-full justify-center"
    >
        <?= $heroicons->scaleHtml('shrink-0', 20, 20, ['aria-hidden' => 'true']); ?>
        <?= $escaper->escapeHtml(__('Compare Products')) ?>
    </a>
</div>
