<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

?>

<div class="pt-4 pb-4 px-6 flex items-center justify-between gap-4">
    <a
        href="<?= $escaper->escapeUrl($block->getUrl('checkout/cart/index')) ?>"
        class="btn btn-primary p-3 flex items-center justify-center rounded"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Shopping Cart')) ?>"
    >
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" viewBox="0 0 24 24" aria-hidden="true"><circle cx="8" cy="21" r="1"></circle><circle cx="19" cy="21" r="1"></circle><path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12"></path></svg>
    </a>
    <a
        href="<?= $escaper->escapeUrl($block->getUrl('wishlist')) ?>"
        class="p-3 rounded hover:bg-primary/10 text-gray-700 flex items-center justify-center"
        aria-label="<?= $escaper->escapeHtmlAttr(__('My Wish List')) ?>"
    >
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" width="24" height="24" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path>
        </svg>
    </a>
    <a
        href="<?= $escaper->escapeUrl($block->getUrl('catalog/product_compare/index')) ?>"
        class="p-3 rounded hover:bg-primary/10 text-gray-700 flex items-center justify-center"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Compare Products')) ?>"
    >
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" width="24" height="24" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3"></path>
        </svg>
    </a>
</div>
