<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Customer\Block\Address\Edit;
use Magento\Customer\ViewModel\Address as AddressViewModel;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use GardenLawn\Company\Helper\Data as CompanyHelper;

/** @var Edit $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var ViewModelRegistry $viewModels */

$companyHelper = $viewModels->require(CompanyHelper::class);
$isB2bCustomer = in_array($companyHelper->getCurrentCustomerGroupId(), $companyHelper->getB2bCustomerGroups());

if ($isB2bCustomer) {
    // For B2B customers, show a simplified form.
    ?>
    <div class="text-2xl mb-6">
        <?= $escaper->escapeHtml(__('Update B2B Address Information')) ?>
    </div>
    <div class="message info">
        <div><?= $escaper->escapeHtml(__('As a B2B customer, your default billing address is automatically synchronized with the CEIDG database. Providing your NIP will update it. A default shipping address will only be created if one does not already exist.')) ?></div>
    </div>
    <form class="form-address-edit"
          action="<?= $escaper->escapeUrl($block->getSaveUrl()) ?>"
          method="post"
          id="form-validate"
    >
        <fieldset class="fieldset">
            <legend class="legend"><span><?= $escaper->escapeHtml(__('Your Information')) ?></span></legend>
            <?= $block->getBlockHtml('formkey') ?>
            <input type="hidden" name="success_url" value="<?= $escaper->escapeUrl($block->getSuccessUrl()) ?>">
            <input type="hidden" name="error_url" value="<?= $escaper->escapeUrl($block->getErrorUrl()) ?>">

            <?= $block->getNameBlockHtml() ?>

            <div class="field field-reserved taxvat required">
                <label class="label" for="vat_id">
                    <span><?= $escaper->escapeHtml(__('Tax/VAT Number')) ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="vat_id"
                           id="vat_id"
                           value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getVatId()) ?>"
                           title="<?= $escaper->escapeHtmlAttr(__('Tax/VAT Number')) ?>"
                           class="form-input w-full"
                           required
                    >
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit"
                        class="action save primary"
                        title="<?= $escaper->escapeHtmlAttr(__('Update Addresses')) ?>">
                    <span><?= $escaper->escapeHtml(__('Update Addresses')) ?></span>
                </button>
            </div>
            <div class="secondary">
                <a class="action back" href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
                    <span><?= $escaper->escapeHtml(__('Go back')) ?></span>
                </a>
            </div>
        </div>
    </form>
    <?php
} else {
    // Original form for non-B2B customers
    /** @var AddressViewModel $addressViewModel */
    $addressViewModel = $block->getViewModel();
    $directoryViewModel = $viewModels->require(\Hyva\Theme\ViewModel\Directory::class);

    $companyBlock = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class);
    $taxvatBlock = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class);
    $phoneBlock = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class);
    $faxBlock = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class);
    $streetLabel = $block->getAttributeData()->getFrontendLabel('street');
    $regionLabel = $block->getAttributeData()->getFrontendLabel('region');
    $showOptionalRegions = $block->getConfig('general/region/display_all');
    ?>
    <div class="text-2xl mb-6">
        <?= $escaper->escapeHtml(__('Customer Address')) ?>
    </div>
    <form class="form-address-edit"
          x-data="initCustomerAddressEdit"
          @private-content-loaded.window="onPrivateContentLoaded"
          @submit="onSubmit"
          action="<?= $escaper->escapeUrl($block->getSaveUrl()) ?>"
          method="post"
          id="form-validate"
          enctype="multipart/form-data"
          data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>"
    >
        <fieldset class="fieldset">
            <legend class="legend"><span><?= $escaper->escapeHtml(__('Contact Information')) ?></span></legend>
            <?= $block->getBlockHtml('formkey') ?>
            <input type="hidden" name="success_url" value="<?= $escaper->escapeUrl($block->getSuccessUrl()) ?>">
            <input type="hidden" name="error_url" value="<?= $escaper->escapeUrl($block->getErrorUrl()) ?>">

            <div class="md:grid grid-cols-2 gap-x-4 gap-y-0">
                <?= $block->getNameBlockHtml() ?>

                <?php if ($companyBlock->isEnabled()): ?>
                    <div class="w-full">
                        <?= $companyBlock->setCompany($block->getAddress()->getCompany())->toHtml() ?>
                    </div>
                <?php endif ?>

                <?php if ($phoneBlock->isEnabled()): ?>
                    <div class="w-full">
                        <?= $phoneBlock->setTelephone($block->getAddress()->getTelephone())->toHtml() ?>
                    </div>
                <?php endif ?>

                <?php if ($faxBlock->isEnabled()): ?>
                    <div class="w-full">
                        <?= $faxBlock->setFax($block->getAddress()->getFax())->toHtml() ?>
                    </div>
                <?php endif ?>
            </div>
        </fieldset>
        <fieldset class="fieldset">
            <legend class="legend w-full"><span><?= $escaper->escapeHtml(__('Address')) ?></span></legend>
            <div class="md:grid grid-cols-2 gap-x-4 gap-y-0">
                <div class="street col-span-full md:grid grid-cols-2 gap-x-4 mb-6">

                    <div class="field field-reserved required">
                        <label for="street_1" class="label">
                            <span><?= /* @noEscape */
                                $streetLabel ?></span>
                        </label>
                        <div class="control">
                            <input type="text"
                                   name="street[]"
                                   required
                                   value="<?= $escaper->escapeHtmlAttr($block->getStreetLine(1)) ?>"
                                   title="<?= /* @noEscape */
                                   $streetLabel ?>"
                                   id="street_1"
                                   class="form-input w-full"
                                   @input.debounce="onChange"
                            >
                        </div>
                    </div>

                    <?php for ($i = 1, $n = $addressViewModel->addressGetStreetLines(); $i < $n; $i++): ?>
                        <div class="field additional">
                            <label class="label" for="street_<?= /* @noEscape */
                            $i + 1 ?>">
                                <span><?= $escaper->escapeHtml(__('Street Address %1', $i + 1)) ?></span>
                            </label>
                            <div class="control">
                                <input type="text" name="street[]"
                                       value="<?= $escaper->escapeHtmlAttr($block->getStreetLine($i + 1)) ?>"
                                       title="<?= $escaper->escapeHtmlAttr(__('Street Address %1', $i + 1)) ?>"
                                       id="street_<?= /* @noEscape */
                                       $i + 1 ?>"
                                       class="form-input w-full"
                                       @input.debounce="onChange"
                                >
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>

                <?php if ($taxvatBlock->isEnabled()): ?>
                    <div class="w-full">
                        <?= $taxvatBlock->setTaxvat($block->getAddress()->getVatId())->toHtml() ?>
                    </div>
                <?php endif; ?>

                <div class="field field-reserved zip w-full" :class="zipFieldClasses">
                    <label class="label" for="zip">
                        <span><?= /* @noEscape */
                            $block->getAttributeData()->getFrontendLabel('postcode') ?></span>
                    </label>
                    <div class="control">
                        <input type="text"
                               name="postcode"
                               x-ref="postcode"
                               value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>"
                               title="<?= /* @noEscape */
                               $block->getAttributeData()->getFrontendLabel('postcode') ?>"
                               id="zip"
                               placeholder="00-000"
                               maxlength="6"
                               :required="isZipRequired"
                               @input.debounce="onChange"
                               data-validate='{"postcode": true}'
                               class="form-input w-full">
                    </div>
                </div>

                <div class="field field-reserved required city w-full">
                    <label class="label" for="city">
                        <span><?= /* @noEscape */
                            $block->getAttributeData()->getFrontendLabel('city') ?></span>
                    </label>
                    <div class="control">
                        <input type="text"
                               name="city"
                               required
                               value="<?= $escaper->escapeHtmlAttr($block->getAddress()->getCity()) ?>"
                               title="<?= $escaper->escapeHtmlAttr(__('City')) ?>"
                               class="form-input w-full"
                               id="city"
                               @input.debounce="onChange">
                    </div>
                </div>

                <div class="field field-reserved required country w-full">
                    <label class="label" for="country">
                        <span><?= /* @noEscape */
                            $block->getAttributeData()->getFrontendLabel('country_id') ?></span>
                    </label>
                    <div class="control">
                        <?php $countries = $block
                            ->getCountryCollection()
                            ->setForegroundCountries($directoryViewModel->getTopCountryCodes())
                            ->toOptionArray();
                        ?>
                        <select name="country_id"
                                id="country"
                                title="<?= /* @noEscape */
                                $block->getAttributeData()->getFrontendLabel('country_id') ?>"
                                required
                                class="form-select"
                                x-ref="country_id"
                                @input.debounce="changeCountry"
                        >
                            <?php foreach ($countries as $country): ?>
                                <option name="<?= /** @noEscape */
                                $country['label'] ?>"
                                        value="<?= /** @noEscape */
                                        $country['value'] ?>"
                                        data-is-zip-required="<?= (isset($country['is_zipcode_optional'])) ? '0' : '1' ?>"
                                        data-is-region-required="<?= (isset($country['is_region_required'])) ? '1' : '0' ?>"
                                    <?= ($block->getCountryId() === $country['value']) ? 'selected="selected"' : '' ?>
                                >
                                    <?= /** @noEscape */
                                    $country['label'] ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>

                <div
                    class="field field-reserved region w-full"
                    x-cloak
                    x-show="showRegionFieldLabel"
                    :class="regionFieldClasses"
                >
                    <label class="label" for="region_id">
                        <span><?= /* @noEscape */
                            $regionLabel ?></span>
                    </label>
                    <div class="control">
                        <template x-if="showRegionField">
                            <select id="region_id" name="region_id"
                                    title="<?= /* @noEscape */
                                    $regionLabel ?>"
                                    class="form-select validate-select region_id"
                                    x-ref="region_id"
                                    :required="isRegionRequired"
                                    @input.debounce="onRegionIdChange"
                            >
                                <option
                                    value=""><?= $escaper->escapeHtml(__('Please select a region, state or province.')) ?></option>
                                <template x-for="regionId in getAvailableRegionIds">
                                    <?php /* in alpine v3, if the bound props update, the template body gets evaluated before the template condition */ ?>
                                    <?php /* because of this it is required to check if availableRegions[regionId] is set */ ?>
                                    <option :value="regionId"
                                            :name="regionName"
                                            x-text="regionName"
                                            :selected="isRegionSelected"
                                    >
                                    </option>
                                </template>
                            </select>
                        </template>
                        <input :type="regionFieldInputType"
                               id="region"
                               name="region"
                               x-ref="region"
                               value="<?= $escaper->escapeHtmlAttr($block->getRegion()) ?>"
                               title="<?= /* @noEscape */
                               $regionLabel ?>"
                               class="form-input w-full"
                               aria-label="<?= /* @noEscape */
                               $regionLabel ?>"
                               :required="isRegionInputRequired"
                               @input.debounce="onChange"
                        >
                    </div>
                </div>
            </div>

            <?= $block->getChildHtml('fieldset_address_info_additional') ?>

            <?php $isDefaultMessages = array_filter([
                $block->isDefaultBilling() ? __("It's a default billing address.") : null,
                $block->isDefaultShipping() ? __("It's a default shipping address.") : null,
            ]) ?>
            <?php if ($isDefaultMessages): ?>
                <div class="message">
                    <?= $escaper->escapeHtml(implode("<br>\n", $isDefaultMessages), ['br']) ?>
                </div>
            <?php endif; ?>
            <?php if (!$block->isDefaultBilling() && $block->canSetAsDefaultBilling()): ?>
                <div class="field choice set billing">
                    <input type="checkbox" id="primary_billing" name="default_billing" value="1" class="checkbox">
                    <label class="label" for="primary_billing">
                        <span><?= $escaper->escapeHtml(__('Use as my default billing address')) ?></span>
                    </label>
                </div>
            <?php else: ?>
                <input type="hidden" name="default_billing" value="1">
            <?php endif; ?>

            <?php if (!$block->isDefaultShipping() && $block->canSetAsDefaultShipping()): ?>
                <div class="field choice set shipping">
                    <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox">
                    <label class="label" for="primary_shipping">
                        <span><?= $escaper->escapeHtml(__('Use as my default shipping address')) ?></span>
                    </label>
                </div>
            <?php else: ?>
                <input type="hidden" name="default_shipping" value="1">
            <?php endif; ?>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit"
                        class="action save primary"
                        data-action="save-address"
                        title="<?= $escaper->escapeHtmlAttr(__('Save Address')) ?>">
                    <span><?= $escaper->escapeHtml(__('Save Address')) ?></span>
                </button>
            </div>
            <div class="secondary">
                <a class="action back" href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
                    <span><?= $escaper->escapeHtml(__('Go back')) ?></span>
                </a>
            </div>
        </div>
    </form>
    <script>
    function initCustomerAddressEdit() {
        return Object.assign(
            {
                directoryData: {},
                availableRegions: {},
                messageTime: 5000,
                fieldsNames: [],
                selectedRegion: '<?= $escaper->escapeJs($block->getRegion() ?: 0) ?>',
                isZipRequired: true,
                isRegionRequired: true,
                showOptionalRegions: <?= $showOptionalRegions ? 'true' : 'false' ?>,
                onPrivateContentLoaded() {
                    const data = this.$event.detail.data;
                    this.directoryData = data['directory-data'] || {};

                    <?php if ($block->getCountryId()): ?>
                    this.setCountry(this.$refs['country_id'], '<?= $escaper->escapeJs($block->getRegion()) ?>');
                    <?php endif; ?>

                },
                setRegionInputValue(regionName) {
                    this.$nextTick(() => {
                        const regionInputElement = this.$refs['region'];
                        if (regionInputElement) {
                            regionInputElement.value = regionName;
                        }
                    })
                },
                setCountry(countrySelectElement, initialRegion) {
                    const selectedOption = countrySelectElement.options[countrySelectElement.selectedIndex];
                    const countryCode = countrySelectElement.value;
                    const countryData = this.directoryData[countryCode] || false;

                    if (!countryData) {
                        this.setRegionInputValue('');
                        return;
                    }

                    this.isZipRequired = selectedOption.dataset.isZipRequired === '1';
                    this.isRegionRequired = selectedOption.dataset.isRegionRequired === '1';

                    this.availableRegions = countryData.regions || {};

                    const initialRegionId = Object.keys(this.availableRegions).filter(regionId => this.availableRegions[regionId].name === initialRegion)[0];
                    this.selectedRegion = initialRegionId || '0';
                    this.setRegionInputValue(initialRegionId && this.availableRegions[initialRegionId].name || '');

                },
                changeCountry(event, initialRegion) {
                    this.setCountry(event.target, initialRegion);
                    this.validateCountryDependentFields();
                    this.onChange(event);
                },
                validateCountryDependentFields() {
                    this.$nextTick(() => {
                        <?php /* Reinitialize validation rules for fields that depend on the country */ ?>
                        this.fields['postcode'] && this.removeMessages(this.fields['postcode'])
                        this.fields['region'] && this.removeMessages(this.fields['region'])
                        delete this.fields['postcode'];
                        delete this.fields['region'];
                        <?php /* Initialize country_id, too, because the postcode validation depends on it */ ?>
                        this.setupField(this.$refs['country_id']);
                        this.setupField(this.$refs['postcode']);
                        this.setupField(this.$refs['region']);
                        this.setupField(this.$refs['region_id']);

                        this.fields['postcode'] && this.validateField(this.fields['postcode']);
                        this.fields['region'] && this.validateField(this.fields['region']);
                        this.fields['region_id'] && this.validateField(this.fields['region_id']);
                    })
                },
                getAvailableRegionIds() {
                    return Object.keys(this.availableRegions);
                },
                hasAvailableRegions() {
                    return Object.keys(this.availableRegions).length > 0;
                },
                showRegionFieldLabel() {
                    return (this.hasAvailableRegions() && this.isRegionRequired) || this.showOptionalRegions;
                },
                showRegionField() {
                    return this.hasAvailableRegions() && (this.isRegionRequired || this.showOptionalRegions);
                },
                onRegionIdChange() {
                    this.selectedRegion = this.$el.value;
                    this.$refs.region.value = this.selectedRegion.length > 0 ?
                        this.availableRegions[this.selectedRegion].name :
                        ''
                    this.onChange(this.$event)
                    this.validateField(this.fields['region'])
                },
                regionName() {
                    return this.availableRegions[this.regionId] && this.availableRegions[this.regionId].name;
                },
                isRegionSelected() {
                    return this.selectedRegion === this.regionId;
                },
                isRegionInputRequired() {
                    return !this.hasAvailableRegions() && !this.showOptionalRegions ? this.isRegionRequired : false;
                },
                zipFieldClasses() {
                    return {
                        required: this.isZipRequired
                    }
                },
                regionFieldClasses() {
                    return {
                        required: this.isRegionRequired
                    }
                },
                regionFieldInputType() {
                    return this.hasAvailableRegions() && (this.isRegionRequired || this.showOptionalRegions) ? 'hidden' : 'text';
                }
            },
            hyva.formValidation(document.getElementById('form-validate'))
        )
    }

    window.addEventListener('alpine:init', () => Alpine.data('initCustomerAddressEdit', initCustomerAddressEdit), {once: true})
    </script>
    <?php $hyvaCsp->registerInlineScript() ?>
<?php } ?>
