<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Block\SortableItem;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Customer\Model\Account\Redirect;
use Magento\Framework\Escaper;

/** @var SortableItem $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */

$label = $block->getLabel() ?: __('Sign In');
$signInId = $escaper->escapeHtmlAttr($block->getNameInLayout());
?>

<script>
    document.addEventListener('DOMContentLoaded', () => {
        const signInLink = document.getElementById('<?= $escaper->escapeJs($signInId) ?>');
        if (signInLink) {
            signInLink.addEventListener('click', () => {
                if (hyva.setCookie) {
                    hyva.setCookie(
                        '<?= $escaper->escapeJs(Redirect::LOGIN_REDIRECT_URL) ?>',
                        window.location.href,
                        1
                    );
                }
            });
        }
    });
</script>
<?php $hyvaCsp->registerInlineScript() ?>
<a
    id="<?= $signInId ?>"
    class="block py-1.5 hover:underline"
    href="<?= $escaper->escapeUrl($block->getUrl('customer/account/index')) ?>"
>
    <?= $escaper->escapeHtml($label) ?>
</a>
