<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\LucideIcons;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);

/** @var Wishlist $wishlistViewModel */
$wishlistViewModel = $viewModels->require(Wishlist::class);

/** @var LucideIcons $lucideIcons */
$lucideIcons = $viewModels->require(LucideIcons::class);

$product = $productViewModel->getProduct();

if (!$wishlistViewModel->isEnabled()) {
    return;
}
?>
<script>
    function initWishlistOnProductView() {
        return {
            addToWishlist() {
                const form = document.getElementById('product_addtocart_form');
                if (!form) return;
                const formData = new FormData(form);
                formData.append('product', '<?= (int)$product->getId() ?>');
                formData.append('uenc', '<?= $escaper->escapeJs($productViewModel->getAddToCartUrl($product)) ?>');

                fetch(BASE_URL + 'wishlist/index/add/', {
                    method: 'POST',
                    body: formData,
                    headers: {
                        'X-Requested-With': 'XMLHttpRequest'
                    }
                }).then(response => {
                    window.location.reload();
                });
            }
        }
    }
</script>
<button type="button"
        class="shrink-0 btn rounded-full p-3 border-transparent bg-gray-200 text-gray-500 hover:border-transparent hover:bg-red-500 hover:text-white"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Wish List') . ' ' . $product->getName()) ?>"
        data-addto="wishlist"
        data-product-id="<?= (int)$product->getId() ?>"
        x-data="initWishlistOnProductView"
        x-defer="intersect"
        @click.prevent="addToWishlist"
>
    <?= $lucideIcons->heartHtml('', 20, 20, ['aria-hidden' => 'true']) ?>
</button>
