<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Checkout\Model\ShippingMethodMetaData;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Checkout\ViewModel\Checkout\Formatter as FormatterViewModel;
use Hyva\Checkout\ViewModel\Checkout\Shipping\MethodList as ViewModel;
use Hyva\Checkout\Magewire\Checkout\Shipping\MethodList as Magewire;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Quote\Api\Data\ShippingMethodInterface;
use Magento\Tax\Helper\Data as TaxHelper;
use Hyva\Theme\ViewModel\Store;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */
/** @var ViewModel $viewModel */
/** @var ShippingMethodInterface $method */
/** @var Magewire $magewire */
/** @var Escaper $escaper */
/** @var TaxHelper $taxHelper */
/** @var Store $storeViewModel */

$viewModel = $viewModels->require(ViewModel::class);
$formatterViewModel = $viewModels->require(FormatterViewModel::class);
$taxHelper = $this->helper(TaxHelper::class);
$storeViewModel = $viewModels->require(Store::class);
$storeId = $storeViewModel->getStoreId();
$methods = $viewModel->getList();
?>
<div id="shipping-methods">
    <?php if ($methods): ?>
        <div id="shipping-method-list" class="flex flex-col space-y-2">
            <?php foreach ($methods as $method): ?>
                <?php if ($method->getAvailable()): ?>
                    <?php $methodCode = $escaper->escapeHtml($method->getMethodCode()) ?>
                    <?php $methodCodeAttr = $escaper->escapeHtmlAttr($method->getMethodCode()) ?>
                    <?php $methodCarrierCode = $escaper->escapeHtmlAttr($method->getCarrierCode()) ?>
                    <?php $methodTitle = $escaper->escapeHtml($viewModel->getMethodTitle($method)) ?>
                    <?php /** @var ShippingMethodMetaData $methodMetaData */ ?>
                    <?php $methodMetaData = $viewModel->getMethodMetaData($block, $method) ?>

                    <div
                        id="shipping-method-option-<?= /* @noEscape */ $methodCode ?>"
                        class="border-2 rounded-md <?= $magewire->method === $methodCarrierCode . '_' . $methodCodeAttr ? 'active bg-primary bg-opacity-10 border-primary' : 'inactive bg-white' ?>"
                        wire:key="<?= /* @noEscape */ $methodCodeAttr ?>"
                        data-disabled="<?= ! $method->getErrorMessage() ? 'false' : 'true' ?>"
                        x-data="hyvaCheckoutShippingMethodOption"
                    >
                        <label class="flex items-center gap-x-2.5 mb-0 p-4 cursor-pointer">
                            <input
                                type="radio"
                                id="shipping-method-<?= /* @noEscape */ $methodCodeAttr ?>"
                                name="shipping-method-option"
                                class="form-radio"
                                value="<?= $escaper->escapeHtmlAttr($methodCarrierCode . '_' . $methodCodeAttr) ?>"
                                wire:model="method"
                                x-bind:disabled="disabled"
                            >

                            <span class="flex flex-col md:flex-row md:flex-1 justify-between items-center gap-4">
                                <span>
                                    <span class="text-gray-700 font-medium break-words hyphens-auto">
                                        <?= /** @noEscape */ $methodTitle ?>
                                    </span>
                                    <span class="block product-price price-box">
                                        <?php if ($taxHelper->displayShippingPriceIncludingTax() || $taxHelper->displayShippingBothPrices()): ?>
                                            <span class="price-including-tax" data-label="<?= $escaper->escapeHtmlAttr(__('Incl. Tax')) ?>">
                                                <span class="price">
                                                    <?= /* @noEscape */ $formatterViewModel->currencyWithLabelingConditions($method->getPriceInclTax(), 'shipping-list-item') ?>
                                                </span>
                                            </span>
                                        <?php endif ?>

                                        <?php if ($taxHelper->displayShippingPriceExcludingTax()
                                            || ($taxHelper->displayShippingBothPrices() && $method->getPriceExclTax() !== $method->getPriceInclTax())): ?>
                                            <span class="price-excluding-tax"
                                                <?php if ($taxHelper->displayShippingBothPrices()): ?>
                                                    data-label="<?= $escaper->escapeHtmlAttr(__('Excl. Tax')) ?>"
                                                <?php endif; ?>
                                            >
                                                <span class="price">
                                                    <?= /* @noEscape */ $formatterViewModel->currencyWithLabelingConditions($method->getPriceExclTax(), 'shipping-list-item') ?>
                                                </span>
                                            </span>
                                        <?php endif ?>
                                    </span>
                                </span>
                                <?php if ($methodMetaData->canRenderIcon() && $iconHtml = $methodMetaData->renderIcon()): ?>
                                    <span class="shrink-0">
                                        <?= /* @noEscape */ $iconHtml; ?>
                                    </span>
                                <?php endif ?>
                            </span>
                        </label>
                        <?php if (($method->getErrorMessage()) || ($viewModel->isCurrentShippingMethod($method, $magewire->method))): ?>
                            <div class="flex-1 space-y-2">
                                <?php if ($method->getErrorMessage()): ?>
                                    <div class="p-4 pt-0">
                                        <div role="alert" class="messages w-full">
                                            <p class="message error mb-0">
                                                <?= $escaper->escapeHtml(__($method->getErrorMessage())) ?>
                                            </p>
                                        </div>
                                    </div>
                                <?php endif ?>

                                <?php if ($viewModel->isCurrentShippingMethod($method, $magewire->method)): ?>
                                    <?php if ($viewModel->hasAdditionalView($block, $method)): ?>
                                        <?php $html = $viewModel->getAdditionalViewBlock($block, $method)->toHtml() ?>
                                        <?php if (! empty($html)): ?>
                                            <div class="p-4 pt-0">
                                                <div id="<?= /* @noEscape */ 'shipping-method-view-' . $methodCodeAttr ?>"
                                                     class="w-full mt-4"
                                                >
                                                    <?= /* @noEscape */ $html ?>
                                                </div>
                                            </div>
                                        <?php endif ?>
                                    <?php endif ?>
                                <?php endif ?>
                            </div>
                        <?php endif ?>
                    </div>
                <?php endif ?>
            <?php endforeach ?>
        </div>
    <?php endif ?>
</div>
