<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\ReCaptcha;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Contact\Block\ContactForm;
use Magento\Contact\Helper\Data as ContactHelper;
use Magento\Framework\Escaper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var ContactForm $block */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var ReCaptcha $recaptcha |null */

$formId = 'contact';

/** @var ContactHelper $contactHelper */
$contactHelper = $this->helper(ContactHelper::class);

// Do not replace this with $viewModels->require(ReCaptcha::class); that would break the dependency
// on the Magento_ReCaptchaContact module
$recaptcha = $block->getData('viewModelRecaptcha');

$storeConfig = $viewModels->require(StoreConfig::class);
$heroicons = $viewModels->require(HeroiconsOutline::class);
$storePhoneNumber = $storeConfig->getStoreConfig('general/store_information/phone') ?? '';
$storeEmail = $storeConfig->getStoreConfig('trans_email/ident_general/email') ?? '';
?>
<div class="flex flex-col md:flex-row justify-between py-8 gap-4">
    <form class="form contact card lg:w-1/2 md:w-2/3 div-bordered-blue"
          action="<?= $escaper->escapeUrl($block->getFormAction()) ?>"
          id="<?= $escaper->escapeHtmlAttr($formId) ?>"
          method="post"
          x-data="gardenLawnHyvathemeForm"
          @submit.prevent="gardenLawnHyvathemeFormSubmitPrevent2"
    >
        <fieldset class="">
            <div class="flex flex-col text-center w-full mb-12">
                <h2 class="sm:text-2xl text-xl font-medium title-font mb-4 text-gray-900">
                    <span><?= $escaper->escapeHtml(__('Write Us')) ?></span>
                </h2>
                <p class="w-full mx-auto leading-relaxed text-base"><?= $escaper->escapeHtml(
                    __('Jot us a note and we’ll get back to you as quickly as possible.')
                ) ?></p>
            </div>
            <div class="flex flex-wrap -m-2">
                <div class="field name required p-2 w-full text-left">
                    <label class="label text-gray-700" for="name">
                        <span><?= $escaper->escapeHtml(__('Name')) ?></span>
                    </label>
                    <input name="name" id="name" required title="<?= $escaper->escapeHtmlAttr(__('Name')) ?>"
                           value="<?= $escaper->escapeHtmlAttr(
                               $contactHelper->getPostValue('name')
                                   ?: $contactHelper->getUserName()
                           ) ?>"
                           class="mt-2 input input-light w-full"
                           type="text"
                           placeholder="<?= $escaper->escapeHtml(__('Name')) ?>"
                    />
                </div>
                <div class="field email required p-2 w-full text-left">
                    <label class="label text-gray-700" for="email">
                        <span><?= $escaper->escapeHtml(__('Email')) ?></span>
                    </label>
                    <input name="email" id="email" required title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                           value="<?= $escaper->escapeHtmlAttr(
                               $contactHelper->getPostValue('email')
                                   ?: $contactHelper->getUserEmail()
                           ) ?>"
                           class="mt-2 input input-light w-full"
                           placeholder="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                           type="email"/>
                </div>
                <div class="field telephone p-2 w-full text-left">
                    <label class="label text-gray-700" for="telephone">
                        <span><?= $escaper->escapeHtml(__('Phone Number')) ?></span>
                    </label>
                    <input name="telephone" id="telephone"
                           title="<?= $escaper->escapeHtmlAttr(__('Phone Number')) ?>"
                           value="<?= $escaper->escapeHtmlAttr(
                               $contactHelper->getPostValue('telephone')
                           ) ?>"
                           class="mt-2 input input-light w-full"
                           placeholder="<?= $escaper->escapeHtmlAttr(__('Phone Number')) ?>"
                           type="text"/>
                </div>
                <div class="field comment required p-2 w-full text-left">
                    <label class="label text-gray-700" for="comment">
                        <span><?= $escaper->escapeHtml(__('What’s on your mind?')) ?></span>
                    </label>
                    <textarea name="comment" id="comment" required
                              title="<?= $escaper->escapeHtmlAttr(__('What’s on your mind?')) ?>"
                              class="mt-2 input input-light w-full h-48 contact-comment" cols="5" rows="1"
                              oninput='this.style.height = "";this.style.height = this.scrollHeight + "px"'><?= $escaper->escapeHtml(
                                  $contactHelper->getPostValue('comment')
                              ) ?></textarea>
                </div>
                <?= $block->getChildHtml('form.additional.info') ?>
                <?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_CONTACT) : '' ?>
            </div>
        </fieldset>
        <div class="w-full">
            <?= $block->getBlockHtml('formkey') ?>
            <button type="submit" title="<?= $escaper->escapeHtmlAttr(__('Submit')) ?>" class="btn btn-primary">
                <span><?= $escaper->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
        <div class="w-full">
            <?= $block->getChildHtml('form.additional.after') ?>
            <?= $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_CONTACT) : '' ?>
        </div>
    </form>
    <div x-data="magento_ContactTemplatesFormMovedScript0">
<?php /** Moved variables previously here to "./Magento_Contact/templates/form-csp-js.phtml" */ ?>
<?php /** References (`$formId`, `$recaptcha`, `$recaptcha->getValidationJsHtml(...)`) */ ?>
</div><div class="card lg:w-1/2 md:w-1/3 div-bordered">
        <h2 class="sm:text-2xl text-xl font-medium title-font mb-4 text-gray-900">
            <span><?= $escaper->escapeHtml(__('Contact Details')) ?></span>
        </h2>
        <h1 class="text-md leading-5 font-semibold tracking-wider uppercase">
            <?php echo $storeConfig->getStoreConfig('general/store_information/name') ?? 'GARDEN LAWN & IRRIGATION<br/>Marcin Piechota'; ?>
        </h1>
        <br/>
        <address>
            <p>NIP PL9910370112</p>
            <p>REGON 383643646</p><br/>
            <?= $escaper->escapeHtml($storeConfig->getStoreConfig('general/store_information/street_line1') ?? 'ul. Namysłowska 2'); ?>
            <br/>
            <?= $escaper->escapeHtml($storeConfig->getStoreConfig('general/store_information/city') ?? 'Dobrzeń Wielki'); ?>
            <br/>
            <?= $escaper->escapeHtml($storeConfig->getStoreConfig('general/store_information/postcode') ?? '46-081'); ?>
            <br/>
            Polska<br/>
        </address>
        <ul>
            <?php if ($storePhoneNumber . '+48 795 997 947'): ?>
                <li class="mt-10">
                    <h2 class="text-md leading-5 font-semibold tracking-wider uppercase">
                        <?= __("Gardening services") ?> / <?= __("Sale") ?>
                    </h2>
                    <?= $heroicons->phoneHtml("w-5 h-5 inline mr-1", 25, 25) ?>
                    <a class="inline"
                       href="tel:<?= $escaper->escapeHtmlAttr(preg_replace("/[^0-9+]/", "", $storePhoneNumber)) ?>">
                        <?= $escaper->escapeHtml($storePhoneNumber); ?>
                    </a>
                </li>
                <li>
                    <?= $heroicons->mailHtml("w-5 h-5 inline mr-1", 25, 25) ?>
                    <a href="mailto:<?= $escaper->escapeHtmlAttr($storeEmail); ?>">
                        <?= $escaper->escapeHtml($storeEmail); ?>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
        <br>
        <div id="google-map"></div>
        </div>
</div>
